Repository commudle/commudle-ng, pull requests merged in 2021-07, with the labels that each got.

#264 Form responses fix
  projects/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  projects/commudle-admin/src/app/feature-modules/events/events.module.ts
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.html
  projects/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  projects/shared-components/data-form-fill/data-form-fill.component.html
  projects/shared-components/discussion-chat/user-message/user-message.component.html
  projects/shared-components/discussion-personal-chat/user-personal-chat-message/user-personal-chat-message.component.html
  projects/shared-components/form-responses/responses-table/responses-table.component.html
  projects/shared-components/shared-components.module.ts
Labels: ready to merge

#292 event updation fix
  projects/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  projects/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.scss
  projects/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
Labels: ready to merge

#285 Community page details section revamp
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  projects/commudle-admin/src/assets/styles/variables.scss
Labels: ready to review, review in progress

#276 Revamp individual community about section
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/public-community-routing.module.ts
  projects/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  projects/shared-components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  projects/shared-pipes/pipes.module.ts
  projects/shared-pipes/safe-html.pipe.ts
Labels: ready to review

#307 fix minor bugs in channels page
  projects/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/services/websockets/community-channel.channel.ts
Labels: ready to review

#305 fix issue of new lines in about me section
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-user-profile.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
Labels: ready to review

#286 Revamp the community speakers section design
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.scss
  projects/commudle-admin/src/assets/styles/variables.scss
Labels: ready to review, review in progress

#304 Use input type time in create event page
  projects/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  projects/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.scss
  projects/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
Labels: ready to merge

#306 add tooltips to session page controls
  projects/shared-modules/hms-video/components/conference/conference.component.html
Labels: ready to merge

#308 Feature individual community page
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/event-resources/event-resources.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.scss
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community/public-community-routing.module.ts
  projects/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  projects/commudle-admin/src/assets/styles/variables.scss
  projects/shared-components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  projects/shared-pipes/pipes.module.ts
  projects/shared-pipes/safe-html.pipe.ts
Labels: ready to review

#294 Create a custom 404 page
  projects/commudle-admin/src/app/app-routing.module.ts
  projects/lib-error-handler/src/lib/components/error404-page/error404-page.component.html
  projects/lib-error-handler/src/lib/components/error404-page/error404-page.component.scss
  projects/lib-error-handler/src/lib/components/error404-page/error404-page.component.spec.ts
  projects/lib-error-handler/src/lib/components/error404-page/error404-page.component.ts
  projects/lib-error-handler/src/lib/lib-error-handler.module.ts
  projects/lib-error-handler/src/lib/lib-error-handler.service.ts
  projects/lib-error-handler/src/public-api.ts
Labels: ready to merge
