Repository commudle/commudle-ng, pull requests merged in 2021-06, with the labels that each got.

#245 Differentiation for expert and normal user profile
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.spec.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-cover-photo/user-cover-photo.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-cover-photo/user-cover-photo.component.scss
  projects/commudle-admin/src/app/feature-modules/users/users.module.ts
  projects/commudle-admin/src/assets/images/User-Profile-Cover-Default.png
  projects/commudle-admin/src/assets/styles/variables.scss
Labels: ready to merge

#250 Fix live status not showing
  projects/commudle-admin/src/app/feature-modules/public-events/components/speaker-session-page/users-list/users-list.component.html
Labels: ready to merge

#249 Toggle switch and speaker card styling fixes
  projects/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.ts
Labels: ready to merge

#259 Styling fix of tags in mobile view
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social-card/user-social-card.component.scss
Labels: ready to merge

#251 Navbar menu items fixes
  projects/commudle-admin/src/app/app.component.html
  projects/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  projects/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
Labels: ready to merge

#256 Fix bugs in User profile and Homepage
  projects/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.html
  projects/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.scss
  projects/commudle-admin/src/app/feature-modules/user-follow/user-follow.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/profile-cards/user-profile-card-medium/user-profile-card-medium.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/profile-cards/user-profile-card-medium/user-profile-card-medium.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-build-card/user-build-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-build-card/user-build-card.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-community-card/user-community-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-community-card/user-community-card.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-contributions.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-contributions.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-lab-card/user-lab-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-lab-card/user-lab-card.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-past-event-card/user-past-event-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-past-event-card/user-past-event-card.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social-card/user-social-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social-card/user-social-card.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social.component.scss
Labels: ready to merge

#266 Stop user profile A/B testing
  projects/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  projects/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
  projects/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.scss
Labels: ready to review

#263 Search-bar fix in event dashboard page
  projects/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  projects/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
  projects/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.ts
Labels: ready to merge

#255 Add title to badge images for SEO
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.html
Labels: ready to review, review in progress

#270 Enable follow option for all users
  projects/commudle-admin/src/app/feature-modules/user-follow/user-follow.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-network/user-network.component.ts
Labels: ready to review

#273 Comments fix
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.html
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.scss
  projects/shared-components/discussion-chat/user-message/user-message.component.html
  projects/shared-components/discussion-chat/user-message/user-message.component.scss
Labels: ready to merge

#272 truncate long username in the context menu
  projects/commudle-admin/src/app/app.component.ts
Labels: ready to merge

#248 Fix cookie window issues
  projects/commudle-admin/src/app/app.component.scss
  projects/commudle-admin/src/app/app.component.ts
  projects/shared-components/cookie-consent/cookie-consent.component.html
Labels: ready to merge

#271 Minor css fixes
  projects/commudle-admin/src/app/feature-modules/labs/components/lab-display-card/lab-display-card.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  projects/shared-components/user-profile-horizontal/user-profile-horizontal.component.scss
  projects/shared-components/user-profile-mini/user-profile-mini.component.scss
Labels: ready to merge

#274 Move contributions and social sections to separate routes
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-contributions/user-contributions.component.ts
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social.component.html
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-social/user-social.component.ts
  projects/commudle-admin/src/app/feature-modules/users/users-routing.module.ts
Labels: ready to merge

#275 Searchbar doesn't close in mozilla firefox browser fix
  projects/commudle-admin/src/app/components/search-bar/search-bar.component.ts
Labels: ready to merge

#279 Create directive to highlight links in plain text
  projects/shared-directives/highlight-links.directive.ts
  projects/shared-directives/shared-directives.module.ts
Labels: ready to review

#282 Add tags to speaker cards
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  projects/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
Labels: ready to merge

#280 Override the border-radius of nb-card
  projects/commudle-admin/src/app/components/home/components/home-builds/home-builds.component.scss
  projects/commudle-admin/src/app/components/home/components/home-communities/home-communities.component.scss
  projects/commudle-admin/src/app/components/home/components/home-events/home-events.component.scss
  projects/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.scss
  projects/commudle-admin/src/app/components/home/components/home-external-feed-links/home-external-feed-links.component.scss
  projects/commudle-admin/src/app/components/home/components/home-head-banner/home-head-banner.component.scss
  projects/commudle-admin/src/app/components/home/components/home-labs/home-labs.component.scss
  projects/commudle-admin/src/app/components/home/components/home-promotions/home-promotions.component.scss
  projects/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  projects/commudle-admin/src/app/feature-modules/external-feed/components/external-feed-hlist-item/external-feed-hlist-item.component.scss
  projects/commudle-admin/src/app/feature-modules/external-feed/components/external-feed/external-feed.component.scss
  projects/commudle-admin/src/app/feature-modules/external-feed/components/feed-item-details/feed-item-details.component.scss
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-details/lab-details.component.scss
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.scss
  projects/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource-discussion/speaker-resource-discussion.component.scss
  projects/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.scss
  projects/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-content/user-content.component.scss
  projects/commudle-admin/src/themes.scss
Labels: ready to merge
