Repository commudle/commudle-ng, pull requests merged in 2021-09, with the labels that each got.

#349 Feature notifications
  projects/commudle-admin/src/app/app.component.ts
  projects/commudle-admin/src/app/app.module.ts
  projects/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  projects/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/community-channels.module.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.ts
  projects/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  projects/commudle-admin/src/app/feature-modules/community-groups/community-groups.module.ts
  projects/commudle-admin/src/app/feature-modules/email-confirmations/email-confirmations.module.ts
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion.component.html
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion.component.scss
  projects/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion.component.ts
  projects/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups.module.ts
  projects/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  projects/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.ts
  projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-chat/session-page-chat.component.ts
  projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-qna/session-page-qna.component.ts
  projects/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.scss
  projects/commudle-admin/src/app/feature-modules/users/users.module.ts
  projects/commudle-admin/src/assets/styles/variables.scss
  projects/lib-error-handler/src/lib/lib-error-handler.module.ts
  projects/shared-services/notifications/notifications.service.ts
  projects/shared-services/notifications/tab-title-notifications.service.ts
  projects/shared-services/session-page-notifications.service.ts
Labels: ready to merge

#350 Channel edit message and CSS fixes
  projects/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/services/websockets/community-channel.channel.ts
  projects/commudle-admin/src/app/services/discussions.service.ts
  projects/commudle-admin/src/assets/styles/variables.scss
  projects/commudle-admin/src/environments/environment.ts
  projects/shared-components/votes-display/votes-display.component.ts
  projects/shared-models/user_message.model.ts
  projects/shared-services/api-routes.constants.ts
Labels: ready to merge

#357 fix: bugs in channels
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.ts
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/send-message-form/send-message-form.component.scss
  projects/commudle-admin/src/app/feature-modules/community-channels/services/websockets/community-channel.channel.ts
  projects/commudle-admin/src/environments/environment.ts
  projects/shared-services/notifications/notifications.service.ts
Labels: ready to review

#362 feat: add follow button to user profile card components
  projects/commudle-admin/src/app/components/home/components/home-builds/home-builds-card/home-builds-card.component.html
  projects/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.ts
  projects/commudle-admin/src/app/feature-modules/user-follow/user-follow.component.ts
  projects/commudle-admin/src/app/feature-modules/users/users.module.ts
  projects/shared-components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  projects/shared-components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  projects/shared-components/shared-components.module.ts
  projects/shared-components/user-follow/user-follow.component.html
  projects/shared-components/user-follow/user-follow.component.scss
  projects/shared-components/user-follow/user-follow.component.spec.ts
  projects/shared-components/user-follow/user-follow.component.ts
Labels: ready to review

#366 Feature badges
  projects/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  projects/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-assign/admin-badges-assign.component.html
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-assign/admin-badges-assign.component.scss
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-assign/admin-badges-assign.component.spec.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-assign/admin-badges-assign.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-form/admin-badges-form.component.html
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-form/admin-badges-form.component.scss
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-form/admin-badges-form.component.spec.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-form/admin-badges-form.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-list/admin-badges-list.component.html
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-list/admin-badges-list.component.scss
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-list/admin-badges-list.component.spec.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-list/admin-badges-list.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges.component.html
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges.component.scss
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges.component.spec.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-page-ads/admin-page-ads-form/admin-page-ads-form.component.html
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-page-ads/admin-page-ads-form/admin-page-ads-form.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/components/admin-page-ads/admin-page-ads-list/admin-page-ads-list.component.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/services/sys-admin-badges.service.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/services/sys-admin-user-badges.service.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  projects/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  projects/commudle-admin/src/environments/environment.ts
  projects/shared-models/badge.model.ts
  projects/shared-models/badge_types.enum.ts
  projects/shared-models/badges.model.ts
  projects/shared-models/enums/user_roles.enum.ts
  projects/shared-models/user_badge.model.ts
  projects/shared-models/user_badges.model.ts
  projects/shared-pipes/pipes.module.ts
  projects/shared-pipes/safe-url.pipe.ts
  projects/shared-services/api-routes.constants.ts
Labels: review in progress

#367 fix: filler text in session page
  projects/shared-components/video-stream-v2/video-stream-v2.component.html
Labels: ready to review
