Repository commudle/commudle-ng, pull requests merged in 2023-05, with the labels that each got.

#952 fix: cookies
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.ts
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.html
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.scss
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.ts
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/student-non-profit-support.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/cookie-preferences/cookie-preferences.component.html
  apps/commudle-admin/src/app/services/community-groups.service.ts
  apps/commudle-admin/src/app/services/cookie-consent.service.ts
  apps/commudle-admin/src/app/services/google-tag-manager.service.ts
  apps/shared-components/cookie-consent/cookie-consent.component.html
  apps/shared-components/cookie-consent/cookie-consent.component.ts
  apps/shared-services/seo.service.ts
Labels: ready to review

#950 refactor: login page popup
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/login-consent-popup/login-consent-popup.component.html
  apps/commudle-admin/src/app/components/login-consent-popup/login-consent-popup.component.scss
  apps/commudle-admin/src/app/components/login-consent-popup/login-consent-popup.component.spec.ts
  apps/commudle-admin/src/app/components/login-consent-popup/login-consent-popup.component.ts
  apps/commudle-admin/src/app/components/login/login.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/communication-preferences/communication-preferences.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/communication-preferences/communication-preferences.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/communication-preferences/communication-preferences.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/communication-preferences/communication-preferences.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/edit-user-profile/edit-user-profile.component.html
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
  apps/commudle-admin/src/app/feature-modules/users/users-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  apps/shared-services/api-routes.constants.ts
  apps/shared-services/email-code.service.ts
  apps/shared-services/lib-authwatch.service.ts
Labels: work in progress

#957 refactor: add new_user value in webengage
  apps/commudle-admin/src/app/components/login/login.component.ts
Labels: ready to review

#956 refactor: fix reload and reorder side bar
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-form/community-group-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/edit-user-profile/edit-user-profile.component.html
Labels: ready to review

#941 fix: question description bug
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.ts
Labels: ready to review

#961 fix: form visibility
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
Labels: ready to merge, ready to review

#960 refactor: push user data in webengage
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-admin-notifications/community-admin-notifications.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list-item/notifications-list-item.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list/notifications-list.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list/notifications-list.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-page/notifications-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/public-community-notifications/public-community-notifications.component.ts
  apps/shared-models/current_user.model.ts
  apps/shared-services/lib-authwatch.service.ts
Labels: ready to merge

#962 fix: responses next prev buttons
  libs/ngx-datatable/src/lib/components/footer/pager.component.ts
Labels: ready to merge, ready to review

#963 fix: volunteer-validation-bug
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.ts
Labels: ready to merge, ready to review

#966 refactor: change expiry date
  apps/commudle-admin/src/app/services/cookie-consent.service.ts
Labels: ready to merge
