Repository commudle/commudle-ng, pull requests merged in 2023-08, with the labels that each got.

#1056 refactor: change heading
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
Labels: ready to merge

#1058 refactor: dynamically set seo title based on query
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.ts
Labels: ready to merge

#1062 fix: login to apply job button
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.html
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.ts
Labels: ready to review

#1063 fix: message button on logged out user
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
Labels: ready to review

#1064 fix: newsletter url
  apps/commudle-admin/src/app/feature-modules/main-newsletters/components/main-newsletter/main-newsletter.component.ts
Labels: ready to review

#1065 style: scroll at talk at events
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.scss
Labels: ready to review

#1069 refactor: logo for GDPR
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1044 style: labs page
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/services/labs.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/shared-components/tag/tag.component.html
  apps/shared-components/tag/tag.component.ts
  apps/shared-components/votes-display/votes-display.component.html
  apps/shared-components/votes-display/votes-display.component.scss
  apps/shared-components/votes-display/votes-display.component.ts
  apps/shared-models/featured-items.model.ts
  libs/shared/models/src/lib/lab.model.ts
  libs/shared/models/src/lib/user.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  tailwind.preset.js
Labels: work in progress

#1071 fix: channel page bugs
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
Labels: ready to merge

#1070 style: listing pages
  apps/commudle-admin/src/app/components/communities/communities-about/communities-about.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-upcoming/public-home-list-speakers-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speakers-header/speakers-header.component.scss
Labels: ready to merge

#1072 fix: builds preview image
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.ts
Labels: ready to merge

#1076 style: large footer on listing pages
  apps/commudle-admin/src/app/components/communities/communities.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
Labels: ready to merge

#1077 style: added view all in upcoming events side card
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-upcoming/public-home-list-speakers-upcoming.component.html
Labels: ready to merge

#1074 feat: implemented gogle places api
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
  apps/commudle-admin/src/app/services/google-places-autocomplete.service.ts
  apps/commudle-admin/src/index.html
  apps/commudle-admin/src/styles.scss
  apps/commudle-admin/tsconfig.app.json
  package-lock.json
  package.json
Labels: ready to merge

#1082 style: email in show form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.html
Labels: ready to merge

#1073 style: public event page
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/collaboration-communities/collaboration-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/sponsors/sponsors.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/public-events-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/commudle-admin/src/app/services/events.service.ts
  apps/shared-components/messages/messages-list/message/message.component.scss
  apps/shared-components/messages/messages-list/messages-list.component.scss
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge
