Repository commudle/commudle-ng, pull requests merged in 2023-02, with the labels that each got.

#815 refactor: set path of sitemap
  apps/commudle-admin/project.json
Labels: ready to review

#817 fix: fix add tags in profile page
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
Labels: ready to review

#819 refactor: fix button in feature about page
  apps/commudle-admin/src/app/components/about/about.component.html
Labels: ready to merge

#821 style: notification popover
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-popover/notifications-popover.component.html
Labels: ready to review

#816 style: changes in error404 page
  apps/commudle-admin/src/app/components/communities/communities-about/communities-about.component.scss
  apps/lib-error-handler/src/lib/components/error404-page/error404-page.component.html
  apps/lib-error-handler/src/lib/components/error404-page/error404-page.component.scss
Labels: ready to merge

#814 style: changes in job-list-page, job-form and user-details
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list.component.html
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  tailwind.preset.js
Labels: ready to review

#806 refactor: change complete profile steps UI/UX
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/stepper/stepper.component.html
  apps/commudle-admin/src/app/components/stepper/stepper.component.scss
  apps/commudle-admin/src/app/components/stepper/stepper.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.scss
  apps/commudle-admin/src/app/services/stepper.service.ts
  package-lock.json
  package.json
Labels: ready to review

#822 Fix: search on pressing enter in search box
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.ts
Labels: ready to merge

#811 feat: add banner in community
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.ts
  apps/shared-models/community.model.ts
Labels: ready to review

#823 feat: add sitemaps with separate URL
  apps/commudle-admin/src/sitemap.xml
Labels: ready to review

#824 refactor: add footer in about page
  apps/commudle-admin/src/app/components/about/about.component.ts
Labels: ready to review

#825 refactor: added auto resize in job form
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/shared-directives/shared-directives.module.ts
  apps/shared-directives/textarea-autoresize.directive.spec.ts
  apps/shared-directives/textarea-autoresize.directive.ts
Labels: ready to review, changes requested

#826 fix: height in live video
  apps/commudle-admin/src/app/app.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page.component.ts
Labels: ready to review

#827 fix: fix mark all as read
  apps/commudle-admin/src/app/feature-modules/notifications/store/notifications.store.ts
Labels: ready to review

#829 fix: Fix blur header image in search bar
  apps/commudle-admin/src/app/feature-modules/search/components/utils/search.utils.ts
Labels: ready to review

#832 style: lab page
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.scss
Labels: ready to review

#830 style: adding login otp placeholder
  apps/commudle-admin/src/app/components/login/login.component.html
  apps/commudle-admin/src/app/components/login/login.component.scss
Labels: ready to review, changes requested

#839 refactor: opening resume on another tab
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-applications/job-applications.component.html
Labels: ready to review

#838 fix: login page title and description
  apps/commudle-admin/src/app/components/login/login.component.ts
Labels: ready to review

#828 refactor: set query param
  apps/commudle-admin/src/app/components/profile-status-bar/profile-status-bar.component.ts
Labels: ready to review

#834 refactor: required tags and add dimensions size of banner image
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
Labels: ready to review

#836 refactor: add volunteer in category
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.html
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/jobs.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/shared-models/job.model.ts
Labels: ready to review

#831 fix: page pagination in job applications
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-applications/job-applications.component.ts
  apps/shared-components/pagination/pagination.component.html
  apps/shared-components/pagination/pagination.component.ts
Labels: ready to review, changes requested

#843 style: search bar
  apps/commudle-admin/src/app/components/navbar/navbar.component.html
Labels: ready to review

#845 refactor: added job toggle api
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job-card/user-job-card.component.ts
  apps/commudle-admin/src/app/services/job.service.ts
  apps/shared-services/api-routes.constants.ts
Labels: ready to review

#842 fix: notifications link
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list-item/notifications-list-item.component.ts
  apps/shared-models/enums/notification_parent_types.enum.ts
  apps/shared-models/notification.model.ts
Labels: ready to review

#846 fix: sign in issue while login
  apps/commudle-admin/src/app/components/login/login.component.ts
Labels: ready to review

#844 refactor: added tag input button
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/shared-components/tag/tag.component.html
  apps/shared-components/tag/tag.component.ts
Labels: ready to review

#847 style: added input placeholder in community edit form
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/shared-components/tag/tag.component.ts
Labels: ready to review

#848 refactor : added noindex on public profile page
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
  apps/shared-models/user.model.ts
Labels: ready to review

#853 refactor: remove noIndex
  apps/commudle-admin/src/app/components/home/home.component.ts
  apps/commudle-admin/src/app/components/login/login.component.ts
Labels: ready to review

#858 style: change layout profile page
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-cover-photo/user-cover-photo.component.scss
  apps/commudle-admin/src/assets/images/User-Profile-Cover-Default.png
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
Labels: changes requested

#856 refactor: mobile view community banner
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
Labels: changes requested

#857 fix: event banner image
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to review, changes requested

#859 fix: changed maxlength of username 20
  apps/shared-modules/mini-user-profile/components/hiring-looking-works-tags/hiring-looking-works-tags.component.html
  apps/shared-modules/mini-user-profile/components/hiring-looking-works-tags/hiring-looking-works-tags.component.scss
  apps/shared-modules/mini-user-profile/components/mini-user-profile/mini-user-profile.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.ts
Labels: ready to review, changes requested

#854 feat: add PR generator Template
  pull_request_template.md
Labels: ready to review
