Repository commudle/commudle-ng, pull requests merged in 2023-09, with the labels that each got.

#1083 Payments-api
  .gitignore
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.scss
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.scss
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/services/communities.service.ts
  apps/shared-components/alert/alert.component.scss
  apps/shared-models/event_data_form_enity_group.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/event-ticket-order.service.ts
Labels: ready to review

#1085 style: builds description
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.ts
Labels: ready to merge

#1080 fix: commuity edit form tag limit
  apps/shared-components/tag/tag.component.html
  apps/shared-components/tag/tag.component.ts
Labels: ready to merge

#1087 refactor: remove circular dependency
  libs/shared/services/src/lib/discount-codes-handler.service.ts
  libs/shared/services/src/lib/event-ticket-order.service.ts
  libs/shared/services/src/lib/payment-setting.service.ts
  libs/shared/services/src/lib/stripe-handler.service.ts
Labels: ready to review

#1088 fix: public events page
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/shared-models/users.model.ts
Labels: ready to review

#1090 style: top publishers card
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.html
Labels: ready to merge

#1091 fix: invalid date on events public page
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
Labels: ready to merge

#1093 Payments api
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/discount-codes-handler.service.ts
  libs/shared/services/src/lib/stripe-handler.service.ts
Labels: ready to review

#1096 Payments api
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.ts
Labels: ready to review

#1092 feat: add dropdown for multiple speakers
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
  apps/shared-models/track-slot.model.ts
Labels: ready to review

#1097 fix: events page bugs
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to merge

#1094 style: separate agenda page
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/events-agenda/events-agenda.component.ts
Labels: ready to merge

#1099 refactor: show event speaker for tracks
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
Labels: ready to merge

#1098 style: place submit button in footer while create new form
  apps/commudle-admin/src/app/app-shared-components/surveys/surveys.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
  apps/shared-components/new-data-form/new-data-form.component.ts
Labels: ready to review

#1100 fix: channels and forums bugs
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/delete-channel/delete-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/new-community-channel/new-community-channel.component.ts
Labels: ready to merge

#1105 fix: all forms for fill
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.html
Labels: ready to merge

#1104 refactor: add empty state form channel and forums
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
Labels: ready to merge

#1102 fix: read more bug in form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  libs/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
Labels: work in progress

#1103 feat: speaker slot in form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/shared-models/data_form_entity_response_group.model.ts
  apps/shared-models/track-slot.model.ts
Labels: ready to review

#1106 fix: set schema for events page
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
  libs/shared/models/src/lib/event.model.ts
Labels: ready to merge

#1109 fix: community channels bugs
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
Labels: ready to review

#1107 feat: filters for form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/services/data-form-entity-response-groups.service.ts
  apps/shared-models/question.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1110 style: session slides upload page
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.html
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.scss
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.ts
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.scss
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/homepage.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.html
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  apps/commudle-admin/src/app/services/speaker-resources.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  libs/shared/models/src/lib/speaker-resource.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1111 style: session slides upload page
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.scss
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.scss
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.ts
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.html
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.scss
  apps/commudle-admin/src/app/feature-modules/speaker-resources/speaker-resources.module.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  libs/shared/models/src/lib/user-stats.model.ts
Labels: ready to merge

#1112 fix: chart and multi search for form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses-graph/event-form-responses-graph.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
Labels: ready to review

#1115 fix: filter in form responses
  apps/commudle-admin/src/app/services/data-form-entity-response-groups.service.ts
Labels: ready to review

#1117 fix: upload pdf
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.ts
Labels: ready to merge

#1118 fix: remove pdf
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.ts
Labels: ready to merge

#1122 fix: dropdown for speaker slots
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.ts
  apps/shared-models/question.model.ts
Labels: ready to merge

#1124 fix: filter form
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.ts
Labels: ready to merge

#1126 style: event registrations
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.scss
Labels: ready to merge

#1125 Style event admin page
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/next-step-card/next-step-card.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/next-step-card/next-step-card.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/next-step-card/next-step-card.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/next-step-card/next-step-card.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
Labels: ready to review

#1123 feat: add upload image section
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/commudle-admin/src/app/services/event-updates.service.ts
  apps/shared-models/event_update.model.ts
  libs/editor/src/lib/components/editor/editor.component.html
  libs/editor/src/lib/components/editor/editor.component.scss
  libs/editor/src/lib/components/editor/editor.component.ts
Labels: ready to merge, ready to review

#1127 fix: ui update notification, event update (public, admin)
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/next-step-card/next-step-card.component.scss
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list-item/notifications-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list/notifications-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/collaboration-communities/collaboration-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.ts
  apps/shared-components/messages/messages-list/messages-list.component.scss
  apps/shared-components/messages/messages.component.ts
  apps/shared-models/enums/notification_sender_types.enum.ts
  libs/editor/src/lib/components/editor/editor.component.scss
Labels: ready to review

#1129 fix: general emailer
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
Labels: ready to review

#1128 refactor: revamp entry pass page
  apps/commudle-admin/src/app/feature-modules/events/components/event-checked-in-list/event-checked-in-list.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-checked-in-list/event-checked-in-list.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-checked-in-list/event-checked-in-list.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-checked-in-list/event-checked-in-list.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.scss
  apps/commudle-admin/src/app/feature-modules/events/events-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/shared-components/back-button/back-button.component.html
  apps/shared-components/back-button/back-button.component.scss
  apps/shared-components/back-button/back-button.component.ts
Labels: ready to review
