Repository commudle/commudle-ng, pull requests merged in 2023-06, with the labels that each got.

#948 refactor: logout navbar
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
Labels: ready to merge

#984 fix: membership-toggle-bug
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.ts
Labels: ready to merge

#985 fix: fixed privacy-consent-bug
  apps/commudle-admin/src/app/components/login-consent-popup/login-consent-popup.component.ts
Labels: ready to merge

#989 refactor: events-listing-page
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.html
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/services/events.service.ts
  apps/commudle-admin/src/styles.scss
  apps/shared-components/banner-image/banner-image.component.html
  apps/shared-components/banner-image/banner-image.component.scss
  apps/shared-components/banner-image/banner-image.component.ts
  apps/shared-models/user.model.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.ts
Labels: work in progress

#983 fix: dashboard inconsistencies
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.scss
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.scss
Labels: work in progress

#982 refactor: speaker session delivered
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-menu.service.ts
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  apps/shared-services/api-routes.constants.ts
Labels: ready to review

#992 style: homepage live session pagination
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events.component.scss
Labels: ready to review

#993 style: fix gap between navbar icons
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
Labels: ready to review

#990 feat: make policy page generic
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.html
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.scss
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.ts
  apps/commudle-admin/src/app/feature-modules/policies/policies-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/policies/policies.module.ts
  apps/commudle-admin/src/app/feature-modules/policies/privacy-policy/privacy-policy.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/policies/privacy-policy/privacy-policy.component.ts
  apps/commudle-admin/src/app/feature-modules/policies/terms-and-conditions/terms-and-conditions.component.html
  apps/commudle-admin/src/app/feature-modules/policies/terms-and-conditions/terms-and-conditions.component.scss
  apps/commudle-admin/src/app/feature-modules/policies/terms-and-conditions/terms-and-conditions.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/policies/terms-and-conditions/terms-and-conditions.component.ts
Labels: ready to merge

#998 style: view-more-events in mobile-view
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.ts
Labels: ready to merge

#997 Fix description bug user profile
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.html
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.scss
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.ts
Labels: ready to review

#1000 fix: fix routing of talk at events
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-past-event-card/user-past-event-card.component.html
  apps/shared-models/event.model.ts
Labels: ready to review

#996 style: buils-card
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
  apps/commudle-admin/src/app/feature-modules/skeleton-screens/components/skeleton-cards/skeleton-cards.component.html
  apps/commudle-admin/src/app/feature-modules/skeleton-screens/components/skeleton-cards/skeleton-cards.component.ts
  apps/commudle-admin/src/app/services/community-builds.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/commudle-admin/src/assets/styles/grid.scss
  apps/shared-components/banner-image/banner-image.component.html
  apps/shared-components/banner-image/banner-image.component.scss
  apps/shared-components/banner-image/banner-image.component.ts
  apps/shared-components/tag/tag.component.html
  apps/shared-components/tag/tag.component.scss
  apps/shared-components/tag/tag.component.ts
  apps/shared-components/votes-display/votes-display.component.html
  apps/shared-components/votes-display/votes-display.component.scss
  apps/shared-components/votes-display/votes-display.component.ts
  apps/shared-models/attached-file.model.ts
  apps/shared-models/featured-items.model.ts
  apps/shared-models/listing-page-header.model.ts
  apps/shared-models/user.model.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-medium/user-profile-card-medium.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-small/user-profile-card-small.component.scss
  apps/shared-services/api-routes.constants.ts
  tailwind.preset.js
Labels: work in progress

#1006 style: resizing events page
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.html
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/build-list-item/build-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-list/community-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-blocked-users/community-blocked-users.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-details/lab-details.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/my-labs/lab-list-item/lab-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/live-sessions/live-sessions.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
  apps/commudle-admin/src/app/services/events.service.ts
  apps/shared-components/badge/badge.component.html
  apps/shared-components/badge/badge.component.scss
  apps/shared-components/badge/badge.component.ts
  apps/shared-components/polls/poll-list-item/poll-list-item.component.html
  apps/shared-components/shared-components.module.ts
  apps/shared-models/community-build.model.ts
  apps/shared-models/lab.model.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/mini-user-profile.module.ts
  tailwind.preset.js
Labels: ready to merge

#1007 style: builds page
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/services/home.service.ts
Labels: ready to merge

#1008 fix: members-speakers-bug
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.scss
Labels: work in progress

#1005 feat: add mini variation of header
  apps/commudle-admin/src/app/app.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
Labels: ready to review
