Repository commudle/commudle-ng, pull requests merged in 2023-07, with the labels that each got.

#1011 style: added layout of listing pages
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.html
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.scss
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
Labels: ready to merge

#1020 style: hide mini footer from session page
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.ts
  apps/commudle-admin/src/app/services/footer.service.ts
Labels: ready to review

#1016 fix: create lab form validation
  apps/commudle-admin/src/app/feature-modules/labs/components/create-lab/create-lab.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/edit-lab/edit-lab.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/edit-lab/edit-lab.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/edit-lab/edit-lab.component.ts
Labels: ready to review

#1018 fix: repetition of builds
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
Labels: ready to review

#1014 refactor: show tags in builds and labs for admin and public
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/build-list-item/build-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/my-labs/lab-list-item/lab-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
Labels: ready to merge

#1035 refactor: remove nbSelect
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
  apps/shared-components/new-data-form/new-data-form.component.ts
  apps/shared-components/shared-components.module.ts
Labels: ready to merge

#1033 Refactor community channels revamp
  apps/commudle-admin/src/app/feature-modules/community-channels/community-channels.module.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.ts
  libs/editor/src/lib/components/editor/editor.component.scss
Labels: ready to merge

#1036 style: form-filling-banner-image
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.scss
Labels: ready to merge

#1037 fix: event tags in create and edit details
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/commudle-admin/src/app/services/events.service.ts
  libs/shared/models/src/lib/event.model.ts
Labels: ready to merge

#1038 style: disable view more button in speakers list
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
Labels: ready to merge

#1032 Revamp-eventAdminPage
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-simple-registration/event-simple-registration.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-simple-registration/event-simple-registration.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-simple-registration/event-simple-registration.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-simple-registration/event-simple-registration.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.html
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.scss
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.ts
  apps/commudle-admin/src/app/feature-modules/reusable-components/reusable-components.module.ts
  apps/shared-components/back-button/back-button.component.html
  apps/shared-components/back-button/back-button.component.scss
  apps/shared-components/back-button/back-button.component.spec.ts
  apps/shared-components/back-button/back-button.component.ts
  libs/shared/models/src/lib/event.model.ts
Labels: work in progress

#1030 refactor: attended members
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/public-home-list-speakers.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/commudle-admin/src/app/services/events.service.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
Labels: ready to merge

#1039 refactor: use input property for userName and userId in follow button
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members-card/attended-members-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  apps/shared-modules/mini-user-profile/components/mini-user-profile/mini-user-profile.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/user-follow/user-follow.component.html
  apps/shared-modules/mini-user-profile/components/user-follow/user-follow.component.ts
Labels: ready to merge

#1047 fix: ux fixes of empty state and volunteers limit
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.html
  apps/commudle-admin/src/app/services/events.service.ts
Labels: ready to merge

#1049 feat: sidebar
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/services/sidebar.service.ts
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
  apps/shared-components/sidebar/sidebar.component.ts
Labels: ready to review

#1050 Revamp event admin page
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
Labels: ready to review

#1053 fix: create-build form bug
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.ts
Labels: ready to merge

#1054 fix: service path
  apps/commudle-admin/src/app/app-shared-components/surveys/surveys.component.ts
  apps/commudle-admin/src/app/services/surveys.service.ts
  libs/shared/services/src/index.ts
Labels: ready to merge

#1046 feat: add featured items
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/featured-projects/featured-projects.component.ts
  apps/commudle-admin/src/app/feature-modules/search/services/search.service.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured-communities/admin-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured-communities/admin-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured-communities/admin-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities-channels/admin-featured-communities-channels.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities-channels/admin-featured-communities-channels.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities-channels/admin-featured-communities-channels.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities-channels/admin-featured-communities-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/delete-featured-item/delete-featured-item.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/delete-featured-item/delete-featured-item.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/delete-featured-item/delete-featured-item.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/delete-featured-item/delete-featured-item.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/services/sys-admin-featured-items.service.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  apps/commudle-admin/src/app/services/featured-items.service.ts
  apps/shared-models/featured-items.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1051 feat: add event clone option
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/events-routing.module.ts
  apps/commudle-admin/src/app/services/events.service.ts
  apps/shared-components/sidebar/sidebar.component.scss
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1057 fix: event volunteer api
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/events-volunteer-list/events-volunteer-list.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.scss
  apps/commudle-admin/src/app/services/events.service.ts
Labels: ready to merge

#1055 feat: fix search for featured items
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
Labels: ready to merge
