Repository commudle/commudle-ng, pull requests merged in 2023-12, with the labels that each got.

#1174 fix: past-event-card
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.scss
Labels: ready to review

#1181 feat: add edit option for event data form entity group
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1180 fix: profile banner image
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-cover-photo/user-cover-photo.component.html
Labels: ready to review

#1183 style: meta description for reading book
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.ts
  apps/shared-models/reading_book.model.ts
Labels: ready to merge

#1186 fix: reading book bug
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.scss
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book-index/reading-book-index.component.scss
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.scss
Labels: ready to review

#1184 style: search page
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/labs-featured-card/labs-featured-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.html
  apps/commudle-admin/src/app/app-shared-components/labs-featured/labs-featured.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.ts
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/commudle-admin/src/app/feature-modules/search/services/search.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  libs/shared/models/src/lib/attached-file.model.ts
Labels: ready to merge

#1187 style: book page
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.scss
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies.module.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.html
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.scss
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book-index/reading-book-index.component.html
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book-index/reading-book-index.component.ts
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.html
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1189 feat: add channels and forums in admin community page
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.html
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-admin-notifications/community-admin-notifications.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-admin-notifications/community-admin-notifications.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-and-surveys.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-and-surveys.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members-list/community-members-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members-list/community-members-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-page/community-page.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-page/community-page.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-payments.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-team/community-team.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
Labels: ready to review

#1190 fix: book and search page bugs
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.scss
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.html
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.scss
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.ts
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1179 Feat community newsletter
  apps/commudle-admin/project.json
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.html
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.scss
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.ts
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter.component.html
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter.component.scss
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-newsletter/community-newsletter.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-newsletter/community-newsletter.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-newsletter/community-newsletter.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-newsletter/community-newsletter.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletter/newsletter.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletter/newsletter.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletter/newsletter.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletter/newsletter.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/commudle-admin/src/app/services/newsletter.service.ts
  apps/shared-models/newsletter.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  package-lock.json
  package.json
Labels: work in progress
