Repository commudle/commudle-ng, pull requests merged in 2023-11, with the labels that each got.

#1150 Integrate sentry angular
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/main.ts
  libs/shared/environments/src/lib/environments.ts
  package-lock.json
  package.json
Labels: ready to merge

#1152 feat: add custom page option in orgs
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.ts
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page.component.html
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-custom-pages/community-group-custom-pages.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-custom-pages/community-group-custom-pages.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-custom-pages/community-group-custom-pages.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-custom-pages/community-group-custom-pages.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-custom-page/community-group-custom-page.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-custom-page/community-group-custom-page.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-custom-page/community-group-custom-page.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-custom-page/community-group-custom-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  apps/commudle-admin/src/app/services/custom-page.service.ts
Labels: ready to merge

#1151 refactor: group formGroups and remove auto close event is completed
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
Labels: ready to merge

#1153 fix: noindex on about page
  apps/commudle-admin/src/app/components/about/about.component.ts
Labels: ready to merge

#1154 style: change heading on students non-profit
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.html
Labels: ready to merge

#1155 fix: sentry_dsn
  libs/shared/environments/src/lib/environments.ts
Labels: ready to review

#1156 style: students rounterlink btn
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
Labels: ready to review

#1158 style: add iso logo in footer
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to review

#1159 style: book public page
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-cta/public-page-cta.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-cta/public-page-cta.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-cta/public-page-cta.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-cta/public-page-cta.component.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-feature-card/public-page-feature-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-layout/public-page-layout.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-layout/public-page-layout.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-layout/public-page-layout.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-layout/public-page-layout.component.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-signup-newsletter/public-page-signup-newsletter.component.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-stats/public-page-stats.component.html
  apps/commudle-admin/src/app/app-shared-components/public-page-stats/public-page-stats.component.scss
  apps/commudle-admin/src/app/app-shared-components/public-page-stats/public-page-stats.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/public-page-stats/public-page-stats.component.ts
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.html
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.scss
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies.module.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.html
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.scss
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/public-book-page-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/public-book-page.module.ts
  apps/commudle-admin/src/app/feature-modules/public-pages/components/public-page-guidelines/public-page-guidelines.component.html
  apps/commudle-admin/src/app/feature-modules/public-pages/components/public-page-guidelines/public-page-guidelines.component.scss
  apps/commudle-admin/src/app/feature-modules/public-pages/components/public-page-guidelines/public-page-guidelines.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-pages/components/public-page-guidelines/public-page-guidelines.component.ts
  apps/commudle-admin/src/app/feature-modules/public-pages/models/guideline-cms.model.ts
  apps/commudle-admin/src/app/feature-modules/public-pages/public-pages-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-pages/public-pages.module.ts
  apps/commudle-admin/src/assets/static-assets.ts
  libs/shared/components/src/lib/components/faq/faq.component.html
  libs/shared/components/src/lib/components/faq/faq.component.scss
Labels: ready to review

#1167 feat: add loader in list of voters
  apps/shared-components/votes-display/voters/voters.component.html
  apps/shared-components/votes-display/voters/voters.component.ts
Labels: work in progress

#1168 fix: scroll bug in channel members
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
Labels: ready to review

#1169 style: ui voter list dialog box
  apps/shared-components/votes-display/voters/voters.component.html
  apps/shared-components/votes-display/voters/voters.component.scss
  apps/shared-components/votes-display/voters/voters.component.ts
Labels: ready to review

#1170 feat: add items in content menu of forums
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.ts
Labels: ready to review

#1171 fix: upcoming events community slug
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.html
Labels: ready to review

#1172 style: testimonial on homepage
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
Labels: ready to review

#1173 style: featured community home page
  apps/commudle-admin/src/app/app-shared-components/featured-community-card-medium/featured-community-card-medium.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-community-card-medium/featured-community-card-medium.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-community-card-medium/featured-community-card-medium.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/featured-community-card-medium/featured-community-card-medium.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-featured-communities/homepage-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-featured-communities/homepage-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-featured-communities/homepage-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/homepage.module.ts
Labels: ready to merge
