Repository commudle/commudle-ng, pull requests merged in 2023-04, with the labels that each got.

#914 style: fixes
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
Labels: ready to merge

#913 refactor: merge speaker members
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  tailwind.preset.js
Labels: ready to review

#916 refactor: validation in community form
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
Labels: ready to review

#886 feat: org page
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/channel-card/channel-card.component.html
  apps/commudle-admin/src/app/app-shared-components/channel-card/channel-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/channel-card/channel-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/channel-card/channel-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/communities-card/communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/communities-card/communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/communities-card/communities-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.ts
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list-card/communities-list-card.component.html
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list-card/communities-list-card.component.spec.ts
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list-card/communities-list-card.component.ts
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-about/community-group-about.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-about/community-group-about.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-communities/community-group-communities.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-communities/community-group-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-communities/community-group-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/public-community-groups/public-community-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/resolvers/community-group-details.resolver.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.ts
  apps/commudle-admin/src/app/services/community-groups.service.ts
  apps/commudle-admin/src/environments/environment.ts
  apps/shared-components/community-badge/community-badge.component.scss
  apps/shared-models/community-group.model.ts
  apps/shared-models/event.model.ts
  apps/shared-services/api-routes.constants.ts
  tailwind.preset.js
Labels: ready to review

#922 fix: fix bugs and add skelton card for admin team
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-about/community-group-about.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-communities/community-group-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/public-community-groups/public-community-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/commudle-admin/src/app/feature-modules/skeleton-screens/components/skeleton-cards/skeleton-cards.component.html
  apps/commudle-admin/src/app/feature-modules/skeleton-screens/components/skeleton-cards/skeleton-cards.component.ts
  apps/commudle-admin/src/app/feature-modules/skeleton-screens/skeleton-screens.module.ts
Labels: ready to review

#927 fix: event card bug
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
Labels: ready to review

#926 fix: job-list-route
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.html
Labels: ready to review

#920 refactor: admin agenda
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/shared-components/shared-components.module.ts
Labels: ready to review

#928 refactor: removed speakers component
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
Labels: ready to review

#930 refactor: admin agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
Labels: ready to review

#931 refactor: memebers loader
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.ts
Labels: ready to merge

#935 fix: background blur image bug
  apps/shared-components/banner-image/banner-image.component.html
Labels: ready to merge

#933 fix: data-form-fill
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.scss
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
Labels: ready to merge, ready to review

#934 fix: registrations validation
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.ts
Labels: ready to merge, ready to review

#938 fix: event description
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.html
Labels: ready to merge, ready to review

#937 refactor: new footer
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.scss
Labels: ready to merge, ready to review

#939 feat: communityGroup admin page
  apps/commudle-admin/src/app/app-shared-components/channel-card/channel-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/admin-team/admin-team.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/admin-team/admin-team.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/admin-team/admin-team.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/admin-team/admin-team.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/channels/channels.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/channels/channels.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/channels/channels.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/channels/channels.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-form/community-group-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-form/community-group-form.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-form/community-group-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/members-list/members-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/members-list/members-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/members-list/members-list.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/members-list/members-list.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.scss
  apps/commudle-admin/src/app/services/community-groups.service.ts
  apps/shared-components/community-badge/community-badge.component.html
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
  apps/shared-components/sidebar/sidebar.component.spec.ts
  apps/shared-components/sidebar/sidebar.component.ts
  apps/shared-models/community-channel.model.ts
  apps/shared-models/community-group.model.ts
  apps/shared-models/community.model.ts
  apps/shared-models/event.model.ts
  apps/shared-models/user.model.ts
  apps/shared-services/api-routes.constants.ts
Labels: work in progress

#942 refactor: Validation on save
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.ts
Labels: ready to merge

#946 feat: set meta tags for community groups tabs
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-about/community-group-about.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-communities/community-group-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-events/community-group-events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.ts
Labels: ready to review

#921 refactor: pricing component
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.scss
Labels: ready to merge

#944 refactor: set no index for test-server
  apps/shared-services/seo.service.ts
Labels: work in progress

#947 refactor: add tags on admin Org page
  apps/commudle-admin/src/app/feature-modules/community-groups/Resolver/community-group-details.resolver.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/admin-team/admin-team.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/channels/channels.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/communities.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-form/community-group-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/members-list/members-list.component.ts
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
Labels: ready to review
