Repository commudle/commudle-ng, pull requests merged in 2023-03, with the labels that each got.

#871 fix: route in jobs and resume
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.ts
Labels: ready to review

#874 style: changed public profile icons to fontawesome
  NX
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-feed/user-feed.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social.component.ts
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-menu.service.ts
  tailwind.preset.js
Labels: ready to review

#864 Feat members list
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-engagement-data/user-engagement-data.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-engagement-data/user-engagement-data.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-community-card/user-community-card.component.scss
  apps/commudle-admin/src/app/services/user_roles_users.service.ts
  apps/shared-models/user.model.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-services/api-routes.constants.ts
Labels: ready to review

#887 fix: search while filter
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
Labels: ready to review

#890 Refactor-webEngage
  apps/commudle-admin/src/app/components/profile-status-bar/profile-status-bar.component.ts
  apps/commudle-admin/src/app/components/stepper/stepper.component.html
  apps/commudle-admin/src/app/components/stepper/stepper.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
Labels: ready to review

#872 style: ux event page
  NX
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.scss
  apps/commudle-admin/src/app/components/stepper/stepper.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-list/community-forms-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-list/community-forms-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-team/community-team.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-team/community-team.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/create-data-form/create-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/create-data-form/create-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/data-forms/data-forms.module.ts
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.scss
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list/notifications-list.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/shared-components/alert/alert.component.html
  apps/shared-components/alert/alert.component.scss
  apps/shared-components/alert/alert.component.spec.ts
  apps/shared-components/alert/alert.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.scss
  apps/shared-components/data-form-fill/data-form-fill.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
  apps/shared-components/new-data-form/new-data-form.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.html
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.scss
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  tailwind.preset.js
Labels: work in progress

#885 style: event-card
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/shared-components/banner-image/banner-image.component.html
  apps/shared-components/banner-image/banner-image.component.scss
  apps/shared-components/banner-image/banner-image.component.spec.ts
  apps/shared-components/banner-image/banner-image.component.ts
  apps/shared-components/shared-components.module.ts
  tailwind.preset.js
Labels: work in progress

#891 Style event card
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
Labels: ready to merge

#892 Style ux event page
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-list/community-forms-list.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/data-forms/data-forms.module.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/community-notifications/community-notifications.component.scss
  apps/shared-components/alert/alert.component.scss
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
  apps/shared-components/new-data-form/new-data-form.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.scss
  apps/shared-components/votes-display/voters/voters.component.html
Labels: ready to merge

#894 style: delete job confirmation popup
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.html
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.scss
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.scss
Labels: ready to merge

#897 fix: show tracks data in admin page
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-stats/community-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.scss
Labels: ready to review

#896 style: job-component-ux
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-applications/job-applications.component.scss
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.scss
Labels: ready to merge

#893 style: registration popup
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/form-groups/form-groups.component.ts
  apps/commudle-admin/src/styles.scss
Labels: ready to merge

#903 style: remove margin of event-details in mobile view
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.scss
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.scss
Labels: ready to merge

#904 refactor: add validation in add-speakers
  apps/commudle-admin/src/app/feature-modules/events/components/event-speakers/event-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-speakers/event-speakers.component.scss
Labels: ready to merge

#907 fix: remove change detection
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/time-blocks/time-blocks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slots/track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
Labels: ready to review

#910 style: user-profile-horizontal
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-team/community-team.component.scss
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.scss
  apps/shared-components/votes-display/voters/voters.component.html
Labels: ready to merge

#911 refactor: rss feed button
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-details/lab-details.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-details/lab-details.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-details/lab-details.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs.module.ts
Labels: ready to merge

#906 fix: update link
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
Labels: changes requested
