Repository commudle/commudle-ng, pull requests merged in 2024-08, with the labels that each got.

#1485 fix: case studies meta data and mobile view fixes
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.ts
Labels: ready to merge

#1486 style: policies pages
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.html
Labels: ready to merge

#1489 feat: fix razorpay transfer created
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.scss
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
  libs/shared/models/src/lib/razorpay-payment.model.ts
  libs/shared/services/src/lib/razorpay.service.ts
Labels: ready to review

#1484 feat: addLink payment detail button
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/payment-logs/payment-logs.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/payment-logs/payment-logs.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/payment-logs/payment-logs.component.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-components/alert/alert.component.html
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/razorpay.service.ts
Labels: ready to review, backend-changes

#1495 feat: check show popup if user fill multi form in same event
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.scss
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.ts
  apps/commudle-admin/src/app/services/data-form-entities.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1494 style: search payment logs table
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
  libs/shared/models/src/lib/razorpay-payment.model.ts
  libs/shared/services/src/lib/razorpay.service.ts
Labels: ready to review

#1496 fix: edfeg search for payment, transfer, user
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
Labels: ready to review

#1498 feat: add search in edfeg list
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-components/paid-form-list/paid-form-list.component.html
  apps/shared-components/paid-form-list/paid-form-list.component.scss
  apps/shared-components/paid-form-list/paid-form-list.component.ts
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
Labels: ready to review

#1502 style: builds and comunities listing page header
  apps/commudle-admin/src/app/components/communities/communities-about/communities-about.component.html
  apps/commudle-admin/src/app/components/communities/communities-about/communities-about.component.scss
  apps/commudle-admin/src/app/components/communities/communities-about/communities-about.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.scss
Labels: ready to review

#1503 refactor: change email for payment support
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
Labels: ready to merge

#1506 feat: fix accounts and show only activated account while selected
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.ts
  libs/shared/models/src/lib/razorpay-account.model.ts
  libs/shared/services/src/lib/razorpay.service.ts
Labels: ready to review, backend-changes

#1507 fix: close mail popup when mail send
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
Labels: ready to review

#1510 refactor: add transfer_id in form responses in event
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.ts
  libs/shared/models/src/lib/event-ticket-order.model.ts
Labels: ready to review, backend-changes

#1513 fix: already marked attendance toast
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.ts
Labels: ready to review

#1514 fix: add phone in update profile
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.html
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
Labels: ready to review

#1483 refactor: upcoming hackathon side card
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.html
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.scss
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.ts
  apps/commudle-admin/src/app/components/communities/communities.component.html
  apps/commudle-admin/src/app/components/communities/communities.component.scss
  apps/commudle-admin/src/app/services/hackathon.service.ts
  libs/shared/models/src/lib/event.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1504 refactor: revamp search page
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects-card/featured-projects-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/location-header/location-header.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/location-header/location-header.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/location-header/location-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/search/components/location-header/location-header.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.ts
  apps/commudle-admin/src/app/feature-modules/search/search-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/commudle-admin/src/assets/styles/grid.scss
  apps/shared-components/newsletter-card/newsletter-card.component.html
  apps/shared-components/newsletter-card/newsletter-card.component.scss
  apps/shared-components/newsletter-card/newsletter-card.component.spec.ts
  apps/shared-components/newsletter-card/newsletter-card.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-models/listing-page-header.model.ts
  apps/shared-models/newsletter.model.ts
  libs/shared/models/src/lib/db-models.enum.ts
Labels: ready to merge

#1519 fix: hackathon response group
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.ts
  apps/commudle-admin/src/app/services/hackathon-response-group.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1516 fix: eto_users bug in paid ticket page
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
Labels: ready to review

#1518 fix: featured communities api
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.ts
Labels: ready to merge

#1520 fix: teammate number while filling hackathon form
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.html
Labels: ready to review

#1521 fix: info box for team in hackathon
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.html
Labels: ready to review

#1522 feat: throw error for duplicate emails in teammates of hackathon
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.ts
Labels: ready to review

#1517 feat: add toggle for allow cancellation
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-models/event_data_form_enity_group.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1525 feat: add filled_by_only_team_lead
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/commudle-admin/src/app/services/hackathon-response-group.service.ts
  apps/shared-components/user-details-form/user-details-form.component.html
  apps/shared-components/user-details-form/user-details-form.component.ts
  apps/shared-models/hackathon-response-group.model.ts
  apps/shared-models/hackathon-user-response.model.ts
Labels: ready to review

#1530 feat: add judge type for hackathon judge
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-control-panel-speaker-judge.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-control-panel-speaker-judge.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-control-panel-speaker-judge.component.ts
  apps/shared-models/hackathon-judge.model.ts
Labels: ready to review

#1527 fix: add button to fill registration form
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.scss
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/email-confirmations/email-confirmations.module.ts
Labels: ready to review

#1531 style: judge type badge in judge card
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-judge-card/hackathon-judge-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-judge-card/hackathon-judge-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.ts
Labels: ready to review

#1529 style: pricing page router link
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.ts
Labels: ready to merge

#1497 refactor: individual chat popup
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.scss
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/user-chats.module.ts
  apps/shared-components/user-profile-mini/user-profile-mini.component.html
  apps/shared-components/user-profile-mini/user-profile-mini.component.scss
  apps/shared-components/user-profile-mini/user-profile-mini.component.ts
  apps/shared-models/discussion-follower.model.ts
Labels: ready to merge

#1534 fix: default channel message
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
Labels: ready to review

#1532 fix: fill hackathon registration form
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
Labels: ready to review

#1533 feat: add button to send CSV
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review, backend-changes

#1535 fix: show all responses for hackathon user responses
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
Labels: ready to review, backend-changes

#1511 feat: add overall round selection mailer in communication tab
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review
