Repository commudle/commudle-ng, pull requests merged in 2024-12, with the labels that each got.

#1676 style: change the limit to 20
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.ts
Labels: ready to merge

#1677 fix: padding of form description
  apps/shared-components/data-form-fill/data-form-fill.component.scss
Labels: ready to merge

#1679 style: schema data on tags
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.ts
Labels: ready to merge

#1681 refactor: add info message for discount code
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
Labels: ready to merge

#1675 style: user connect
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-personal-connect/user-personal-connect.component.html
  apps/commudle-admin/src/app/app-shared-components/user-personal-connect/user-personal-connect.component.scss
  apps/commudle-admin/src/app/app-shared-components/user-personal-connect/user-personal-connect.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/user-personal-connect/user-personal-connect.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/community-channels.module.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.html
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/public-hackathon.module.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.scss
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/shared-components.module.ts
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.html
  apps/shared-components/user-profile-horizontal/user-profile-horizontal.component.scss
  apps/shared-components/user-profile-mini/user-profile-mini.component.html
  apps/shared-components/user-profile-mini/user-profile-mini.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-small/user-profile-card-small.component.html
  apps/shared-modules/mini-user-profile/mini-user-profile.module.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/models/src/lib/user.model.ts
Labels: ready to merge

#1682 style: event sponsor logo
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.scss
Labels: ready to review

#1684 style: user-personal-connect
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/community-channels.module.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/public-hackathon.module.ts
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-modules/mini-user-profile/mini-user-profile.module.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/user-personal-connect/user-personal-connect.component.html
  libs/shared/components/src/lib/components/user-personal-connect/user-personal-connect.component.scss
  libs/shared/components/src/lib/components/user-personal-connect/user-personal-connect.component.spec.ts
  libs/shared/components/src/lib/components/user-personal-connect/user-personal-connect.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
Labels: ready to merge

#1686 style: optimise current user subscription
  apps/commudle-admin/src/app/app.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/components/home/components/home-communities/home-communities.component.ts
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
  apps/commudle-admin/src/app/components/navbar/navbar.component.ts
  apps/commudle-admin/src/app/components/push-notification/push-notification.component.ts
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.ts
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.ts
  apps/commudle-admin/src/app/components/stepper/stepper.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/my-community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-list/community-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/discussion-community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/join-by-token/join-by-token.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/email-unsubscribe/email-unsubscribe.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/homepage-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/my-job-applications/my-job-applications.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-step/lab-step.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/my-labs/my-labs.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-list/notifications-list.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/notifications-page/notifications-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/auto-attendance/auto-attendance.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-viewers/session-page-viewers.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.ts
  apps/commudle-admin/src/app/feature-modules/recommendations/components/recommended-builds/recommended-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/recommendations/components/recommended-communities/recommended-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/recommendations/components/recommended-labs/recommended-labs.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-user-profile.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
Labels: ready to merge

#1688 style: optimise logo image path
  apps/commudle-admin/src/app/app-shared-components/communities-card/communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/components/speaker-resource-form/speaker-resource-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events-card/homepage-events-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/public-community-hackathons/public-community-hackathons.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/collaboration-communities/collaboration-communities.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-community-card/user-community-card.component.html
Labels: ready to merge

#1689 style: discount code list on button
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
  libs/shared/models/src/lib/discount-code.model.ts
Labels: ready to review

#1685 feat: add scroll pagination in users chat list
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/user-chats.module.ts
  apps/shared-components/services/s-discussions.service.ts
Labels: ready to review, backend-changes

#1687 feat: profanity api for create and index
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-controls/community-controls.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/services/profanity.service.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  libs/shared/models/src/index.ts
  libs/shared/models/src/lib/profanity.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1691 style: optimise logo image
  apps/commudle-admin/src/app/components/home/components/home-events/home-events-card/home-events-card.component.html
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-list/community-list.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/collaboration-community/collaboration-community.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/rsvp/rsvp.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/user-role-confirmation/user-role-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-details/session-page-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-details/session-page-details.component.ts
  apps/shared-components/community-badge/community-badge.component.html
Labels: ready to merge

#1692 style: optimise current user subscription
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/discussion-community-channel/community-channel-message/community-channel-message.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/social-links/social-links.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-cover-photo/user-cover-photo.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-feed/user-feed.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job-card/user-job-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume-card/user-resume-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history-card/user-work-history-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history.component.ts
  apps/shared-components/discussion-personal-chat/discussion-personal-chat.component.ts
  apps/shared-components/flags-display/flags-display.component.ts
  apps/shared-components/messages/messages.component.ts
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
  apps/shared-components/polls/polls.component.ts
  apps/shared-components/qna/qna.component.ts
  apps/shared-components/user-details-form/user-details-form.component.ts
  apps/shared-components/user-visit-tracker/user-visit-tracker.component.ts
  apps/shared-components/votes-display/votes-display.component.ts
  apps/shared-modules/hms-video/components/hms-video/hms-video.component.ts
  apps/shared-modules/mini-user-profile/components/user-follow/user-follow.component.ts
Labels: ready to merge

#1690 style: discount code list table
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
  libs/shared/models/src/lib/discount-code.model.ts
Labels: ready to merge

#1693 refactor: add discount code used count and loader for fetch info
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
  libs/shared/models/src/lib/discount-code.model.ts
Labels: ready to review

#1695 fix: add optional chaining for community logo image path
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
Labels: ready to merge

#1696 feat: add pagination in user communities list
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-community-card/user-community-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  apps/shared-components/community-badge/community-badge.component.html
Labels: ready to review

#1700 fix: meta tag of communities
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list.component.ts
Labels: ready to merge

#1699 feat: instagram in community
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  libs/shared/models/src/lib/community.model.ts
Labels: ready to review

#1701 refactor: blogs page
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs.module.ts
  apps/shared-components/share-button/share-button.component.html
  apps/shared-components/share-button/share-button.component.ts
  apps/shared-services/cms.service.ts
Labels: ready to merge
