Repository commudle/commudle-ng, pull requests merged in 2024-06, with the labels that each got.

#1379 fix: no index for deactivated profile
  apps/commudle-admin/src/app/app-shared-components/user-consents/hackathon-registration-consent/hackathon-registration-consent.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
Labels: ready to merge

#1378 refactor: update consents
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-community-organizer-consent/accept-community-organizer-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-event-form-registration-consent/accept-event-form-registration-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-event-one-click-registration-consent/accept-event-one-click-registration-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-event-volunteer-consent/accept-event-volunteer-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-single-click-registration-speaker-consent/accept-single-click-registration-speaker-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/join-channel-consent/join-channel-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/join-community-consent/join-community-consent.component.html
Labels: ready to review

#1380 fix: no index for deactivated profile
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
Labels: ready to review

#1312 refactor: features section
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features-content/features-content.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features-content/features-content.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features-content/features-content.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features-content/features-content.component.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.ts
  apps/commudle-admin/src/app/feature-modules/features/features-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/features/features.module.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies.module.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/shared-models/features.model.ts
  apps/shared-services/cms.service.ts
  apps/shared-services/responsive.service.ts
Labels: ready to merge

#1381 fix: profile index while switching profile
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
Labels: ready to review

#1382 Style-event-registration
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
Labels: ready to review

#1383 fix: case-study solution
  apps/commudle-admin/src/app/feature-modules/case-study/case-study.module.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.ts
  apps/shared-models/case-study.model.ts
Labels: work in progress

#1385 style: case study cards
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.scss
Labels: ready to merge

#1386 fix: disable fields when event is not editable
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/user-event-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/shared-components/messages/messages.component.html
  apps/shared-components/messages/messages.component.scss
  apps/shared-models/discussion.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/discussion.service.ts
Labels: ready to review

#1373 feat: remove all roles of particular community while exiting community
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.ts
  apps/commudle-admin/src/app/services/user_roles_users.service.ts
Labels: ready to review

#1388 style: community group admin page
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/community/community.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/communities/events/events.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-home/community-group-home.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups-routing.module.ts
  apps/commudle-admin/src/app/services/community-groups.service.ts
  apps/shared-components/sidebar/sidebar.component.html
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1392 fix: category type in featured items
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.ts
Labels: ready to review

#1393 refactor: typo load more button in channels
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.html
Labels: ready to review

#1394 feat: add event collaboration badges (community)
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-medium-card/event-medium-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-team/community-group-team.component.ts
  apps/commudle-admin/src/app/services/community-groups.service.ts
  libs/shared/models/src/lib/event.model.ts
Labels: ready to review

#1396 style: hackathon dark mode btn
  apps/shared-components/hackathon-cards/hackathon-medium-card/hackathon-medium-card.component.scss
Labels: ready to merge

#1399 style: case study
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.scss
Labels: ready to merge

#1387 style: features section page
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features-content/features-content.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features-index/features-index.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.scss
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1398 feat: default channel on community about
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/communities-channels/communities-channels.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/communities-channels/communities-channels.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/communities-channels/communities-channels.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/communities-channels/communities-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/community-group-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/org-channels/org-channels.component.html
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/org-channels/org-channels.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/org-channels/org-channels.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-channels/org-channels/org-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community-groups/public-community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/shared-directives/longpress.directive.ts
  apps/shared-directives/shared-directives.module.ts
  libs/editor/src/lib/components/editor/editor.component.scss
  libs/shared/components/src/lib/components/channel-discussion/channel-discussion.component.html
  libs/shared/components/src/lib/components/channel-discussion/channel-discussion.component.scss
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.scss
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.scss
  libs/shared/components/src/lib/components/vote/vote.component.scss
  libs/shared/models/src/lib/community-channel.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/community-channels.service.ts
Labels: ready to review

#1401 fix: community channel members count
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  libs/shared/models/src/lib/community-channel.model.ts
Labels: ready to review

#1402 fix: banner image size upto 3 mb
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.ts
Labels: ready to review

#1403 style: newsletter empty state
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletters.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1404 style: help section
  apps/commudle-admin/src/app/app-shared-components/help-dictionary-iframe/help-dictionary-iframe.component.html
  apps/commudle-admin/src/app/app-shared-components/help-dictionary-iframe/help-dictionary-iframe.component.scss
  apps/commudle-admin/src/app/app-shared-components/help-dictionary-iframe/help-dictionary-iframe.component.ts
  apps/commudle-admin/src/app/app-shared-components/help-section/help-section.component.scss
  apps/commudle-admin/src/app/app.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.scss
  libs/shared/services/src/lib/help-dictionary.store.ts
Labels: ready to merge

#1217 Angular 16 upgrade
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierignore
  .vscode/extensions.json
  README.md
  apps/commudle-admin-e2e/.eslintrc.json
  apps/commudle-admin-e2e/cypress.config.ts
  apps/commudle-admin-e2e/project.json
  apps/commudle-admin-e2e/src/e2e/app.cy.ts
  apps/commudle-admin-e2e/src/fixtures/example.json
  apps/commudle-admin-e2e/src/support/commands.ts
  apps/commudle-admin-e2e/src/support/e2e.ts
  apps/commudle-admin-e2e/tsconfig.json
  apps/commudle-admin/.eslintrc.json
  apps/commudle-admin/jest.config.ts
  apps/commudle-admin/ngsw-config.json
  apps/commudle-admin/project.json
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app.component.scss
  apps/commudle-admin/src/app/app.component.spec.ts
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list-actions/community-forms-list-actions.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list-stats/community-forms-list-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list.component.ts
  apps/commudle-admin/src/main.ts
  apps/commudle-admin/src/polyfills.ts
  apps/commudle-admin/src/styles.scss
  apps/commudle-admin/src/test-setup.ts
  apps/commudle-admin/tailwind.config.js
  apps/commudle-admin/tsconfig.app.json
  apps/commudle-admin/tsconfig.editor.json
  apps/commudle-admin/tsconfig.json
  apps/commudle-admin/tsconfig.spec.json
  decorate-angular-cli.js
  jest.config.ts
  jest.preset.js
  libs/editor/src/lib/components/editor/editor.component.scss
  nx.json
  package-lock.json
  package.json
  tailwind.preset.js
  tsconfig.base.json
Labels: ready to merge

#1412 fix: builds decription bug
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
Labels: ready to merge

#1415 fix: hosrizontal scroll in ios
  apps/commudle-admin/src/styles.scss
Labels: ready to merge

#1416 refactor: help section
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
Labels: ready to merge

#1419 style: whats-new
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new-card/whats-new-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.html
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.scss
Labels: ready to merge

#1418 fix: dark mode labs
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.scss
Labels: ready to merge

#1417 style: fragments home event page
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to merge

#1413 feat: get community members and channels
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/member/member.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  libs/shared/components/src/lib/components/channel-discussion/channel-discussion.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.scss
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/services/community-channel-handler.service.ts
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/models/src/lib/community-channel.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/community-channel-manager.service.ts
  libs/shared/services/src/lib/community-channels.service.ts
Labels: ready to review

#1422 fix: upcoming pagination
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
  apps/commudle-admin/src/app/services/events.service.ts
Labels: work in progress

#1423 fix: events page
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
  libs/shared/services/src/lib/seo.service.ts
Labels: ready to review

#1425 fix: agenda location loader
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
Labels: ready to review

#1424 fix: community channel admins list
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/community-channels.service.ts
Labels: ready to review

#1426 feat: add voter in vote component
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.html
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.scss
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.spec.ts
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.ts
  libs/shared/components/src/lib/components/vote/vote.component.html
  libs/shared/components/src/lib/components/vote/vote.component.ts
  libs/shared/components/src/lib/components/vote/voters/voters.component.html
  libs/shared/components/src/lib/components/vote/voters/voters.component.scss
  libs/shared/components/src/lib/components/vote/voters/voters.component.spec.ts
  libs/shared/components/src/lib/components/vote/voters/voters.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/services/src/lib/vote.service.ts
Labels: ready to review

#1428 fix: sticky position
  apps/commudle-admin/src/styles.scss
Labels: ready to review

#1427 feat: add community newsletter sitemap
  apps/commudle-admin/src/sitemap.xml
Labels: ready to review

#1430 refactor: restrict image size 3 mb and content type
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/edit-lab/edit-lab.component.ts
Labels: ready to review
