Repository commudle/commudle-ng, pull requests merged in 2024-09, with the labels that each got.

#1541 fix: meta data of devrel-aggencies
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
Labels: ready to merge

#1540 fix: angular2 smart table
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-public-page/community-events-list-public-page.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.ts
Labels: ready to review

#1538 fix: rzp discount code time and min max value
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
Labels: ready to review

#1543 style: devrel aggencies prefered parterens
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.scss
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies.module.ts
  apps/shared-models/preferred-partners.model.ts
Labels: ready to merge

#1523 refactor speakers page
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.html
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/speaker-slides-card/speaker-slides-card.component.html
  apps/commudle-admin/src/app/app-shared-components/speaker-slides-card/speaker-slides-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/speaker-slides-card/speaker-slides-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/speaker-slides-card/speaker-slides-card.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speakers-header/speakers-header.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/public-home-list-speakers-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/public-home-list-speakers.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.ts
  apps/commudle-admin/src/app/services/events.service.ts
  apps/commudle-admin/src/app/services/speaker-resources.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: work in progress

#1544 style: entry pass incorrect sound
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.ts
Labels: work in progress

#1545 style: pdf iframe
  apps/commudle-admin/src/app/app-shared-components/speaker-slides-card/speaker-slides-card.component.html
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1548 fix: disable private channel as default if it's private
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.html
Labels: ready to review

#1547 fix: reset form visibility if through error
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
Labels: ready to review

#1546 refactor: disable form change dropdown if it have form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.ts
Labels: ready to review

#1551 fix: alignment and cfp text
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.html
Labels: ready to merge

#1552 fix: mobile inconsisitency
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history-card/user-work-history-card.component.scss
Labels: ready to merge

#1554 style: homepage dashboard card
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-featured-communities/homepage-featured-communities.component.scss
Labels: ready to merge

#1558 fix: change bulk status
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
Labels: ready to review

#1556 style: add read more to description of devrel aggencies
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.scss
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/public-agencies.module.ts
Labels: ready to merge

#1555 style: add users 4 sitemap
  apps/commudle-admin/src/sitemap.xml
Labels: ready to merge

#1553 feat: reset discount code on payment failed
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/event-ticket-order.service.ts
Labels: ready to review

#1389 feat: community auth token for streaming
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-streaming/event-streaming.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-streaming/event-streaming.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-streaming/event-streaming.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/assets/images/livestream_dashboard.webp
  libs/auth/src/lib/auth.service.ts
  libs/auth/src/lib/directives/google-signin-button.directive.ts
  libs/auth/src/lib/entities/base-login-provider.ts
  libs/auth/src/lib/entities/login-provider.ts
  libs/auth/src/lib/entities/social-user.ts
  libs/auth/src/lib/providers/email-login-provider.ts
  libs/auth/src/lib/providers/google-login-provider.ts
  libs/auth/src/lib/providers/youtube-login-provider.ts
  package-lock.json
  package.json
Labels: backend-changes

#1561 fix: application review scroll
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
Labels: ready to review

#1563 refactor: rename time_zone to timezone
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dates-form/hackathon-control-panel-dates-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dates-form/hackathon-control-panel-dates-form.component.ts
  apps/shared-models/hackathon.model.ts
  libs/shared/models/src/lib/hackathon.model.ts
Labels: ready to review

#1562 style: pagination in responses table
  libs/ngx-datatable/src/lib/components/datatable.component.scss
  libs/ngx-datatable/src/lib/components/footer/footer.component.ts
  libs/ngx-datatable/src/lib/components/footer/pager.component.ts
  libs/ngx-datatable/src/lib/ngx-datatable.module.ts
  libs/ngx-datatable/src/lib/themes/bootstrap.scss
  libs/ngx-datatable/src/lib/themes/dark.scss
  libs/ngx-datatable/src/lib/themes/material.scss
Labels: ready to merge

#1565 style: pagination pages bug fix
  libs/ngx-datatable/src/lib/components/datatable.component.scss
  libs/ngx-datatable/src/lib/components/footer/footer.component.ts
  libs/ngx-datatable/src/lib/components/footer/pager.component.ts
Labels: ready to merge

#1566 style: cfp card alignment issue
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.html
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.scss
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.scss
Labels: ready to merge

#1567 fix: remove from channel, remove from admin roles in channel
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
Labels: ready to review

#1568 refactor: update text for add judge or speaker
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-control-panel-speaker-judge.component.html
Labels: ready to review

#1571 fix: layout for edit and delete forum
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.ts
  libs/shared/services/src/lib/community-channel-manager.service.ts
Labels: ready to review

#1572 fix: update rzp transfer at real time
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
  libs/shared/services/src/lib/razorpay.service.ts
Labels: ready to review

#1573 refactor: fix scroll in payment logs and show time with date
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.scss
Labels: ready to review

#1577 feat: add icon for identify default channel
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
Labels: ready to review

#1579 fix: edit community newsletter
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter.component.html
Labels: ready to review

#1582 fix: schema data for hackathon faq
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
  apps/shared-components/faq-card/faq-card.component.ts
  apps/shared-components/faq-control-panel/faq-control-panel.component.ts
Labels: ready to review

#1583 fix: form list with angular2 smart table
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list.component.ts
Labels: ready to review
