Repository commudle/commudle-ng, pull requests merged in 2024-10, with the labels that each got.

#1585 refactor: dashboard
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.html
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.ts
  apps/shared-services/feed.service.ts
Labels: ready to merge

#1591 refactor: dashboard
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.html
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-profile/user-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/dashboard.module.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-dashboard/userprofile-details/userprofile-details.component.scss
Labels: ready to merge

#1590 style: fix judge card style for hackathon
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.scss
Labels: ready to review

#1588 fix: layout and add loading or disable button as per requirements
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-status-filter-general-emails/hackathon-status-filter-general-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-status-filter-general-emails/hackathon-status-filter-general-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-winner-announcement-emailer/hackathon-winner-announcement-emailer.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-winner-announcement-emailer/hackathon-winner-announcement-emailer.component.ts
Labels: ready to review

#1586 feat: add prizes on hackathon project cards
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-projects/public-hackathon-projects.component.html
  apps/shared-components/build-card/build-card.component.html
  apps/shared-components/build-card/build-card.component.scss
  apps/shared-components/build-card/build-card.component.ts
Labels: ready to review, backend-changes

#1575 fix: hackathon submit project and edit form
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-registration/public-hackathon-registration.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-registration/public-hackathon-registration.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-registration/public-hackathon-registration.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.html
Labels: help wanted, ready to review

#1593 feat: add lean-qr
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.ts
  package-lock.json
  package.json
Labels: ready to review

#1594 fix: upcoming and past hackathon order
  apps/commudle-admin/src/app/feature-modules/public-community/components/public-community-hackathons/public-community-hackathons.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.scss
  apps/commudle-admin/src/app/services/hackathon.service.ts
  apps/shared-components/hackathon-cards/hackathon-large-card/hackathon-large-card.component.scss
Labels: ready to review, backend-changes

#1592 style: dashboard
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.html
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/dashboard.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/shared-components/hackathon-cards/hackathon-large-card/hackathon-large-card.component.scss
  apps/shared-components/hackathon-cards/hackathon-medium-card/hackathon-medium-card.component.html
  apps/shared-services/feed.service.ts
  libs/shared/models/src/index.ts
  libs/shared/models/src/lib/activity-feed.model.ts
  libs/shared/models/src/lib/db-models.enum.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1597 fix: import hackathonUserResponse model
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-project-details-form/public-hackathon-project-details-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.ts
  apps/shared-components/user-details-form/user-details-form.component.ts
  apps/shared-models/hackathon-user-responses.model.ts
Labels: ready to review

#1601 fix: edit channel messages
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.scss
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.scss
Labels: ready to review

#1603 fix: speaker session slot in dark mode
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
Labels: ready to review

#1602 refactor: fix edit description in forms
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.ts
Labels: ready to review

#1604 fix: attended members initial state for dropdown
  apps/commudle-admin/src/app/feature-modules/public-events/components/attended-members/attended-members.component.html
Labels: ready to review

#1605 fix: round channels in user hackathon dashboard
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1606 refactor: add info info box for linking bank account
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
Labels: ready to review

#1608 refactor: pricing page
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.scss
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
  apps/commudle-admin/src/app/feature-modules/pricing/pricing.module.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/shared-models/enums/cms.enum.ts
  apps/shared-models/pricing-features.model.ts
Labels: ready to merge

#1600 style: dashboard
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.html
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/dashboard-updates/dashboard-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/dashboard.module.ts
  apps/shared-components/hackathon-cards/hackathon-large-card/hackathon-large-card.component.html
  apps/shared-models/data_form_entity_response_group.model.ts
  libs/shared/models/src/lib/db-models.enum.ts
Labels: ready to merge

#1611 feat: add instgram in user
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/social-links/social-links.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/social-links/social-links.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.ts
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
  libs/shared/models/src/lib/user.model.ts
Labels: ready to review

#1612 style: attach form
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.ts
Labels: ready to review

#1617 fix: channel edit message content
  libs/editor/src/lib/components/editor/editor.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.ts
  libs/shared/components/src/lib/services/community-channel-handler.service.ts
Labels: ready to review

#1616 fix: form fill text in public event page
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.scss
Labels: ready to review

#1620 merge request for angular 16 from test-server
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.scss
  libs/editor/src/lib/components/editor/editor.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.ts
  libs/shared/components/src/lib/services/community-channel-handler.service.ts
Labels: ready to merge

#1621 fix: hackathon registration link
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.ts
Labels: ready to review

#1619 refactor: add alert message for bulk status change in event registration
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
Labels: ready to review

#1618 fix: channel and hackathon bugs
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/archive/archive.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/archive/archive.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/delete-channel/delete-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/delete-channel/delete-channel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/invite-form/invite-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/invite-form/invite-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/join-by-token/join-by-token.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/join-by-token/join-by-token.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-channels/hackathon-control-panel-channels.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.routing.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-channels/public-hackathon-channels.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/public-hackathon.routing.ts
  libs/shared/components/src/lib/components/channel-discussion/channel-discussion.component.html
  libs/shared/components/src/lib/components/channel-discussion/channel-discussion.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.ts
  libs/shared/services/src/lib/community-channel-manager.service.ts
Labels: ready to review

#1613 refactor: pricing page
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.scss
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
  apps/commudle-admin/src/app/feature-modules/pricing/pricing.module.ts
  apps/shared-models/pricing-features.model.ts
Labels: ready to merge
