Repository commudle/commudle-ng, pull requests merged in 2024-11, with the labels that each got.

#1632 style: add full date in comments
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/messages/messages-list/message/message.component.ts
  apps/shared-components/messages/messages-list/messages-list.component.html
Labels: ready to merge

#1634 refactor: add message for form close automation in paid forms
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
Labels: ready to review

#1640 style: case study order by
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.ts
Labels: ready to review

#1641 feat: form response filter for user engagement data
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members/community-members.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-engagement-data/user-engagement-data.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-engagement-data/user-engagement-data.component.ts
  apps/commudle-admin/src/app/services/data-form-entity-response-groups.service.ts
  apps/shared-models/data_form_entity_response_group.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1643 style: text for user engagement filter
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
Labels: ready to merge

#1644 fix: event list order by name for user engagement filter
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
Labels: ready to review

#1635 fix: custom pages router-link
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page.component.html
Labels: ready to merge

#1647 refactor: show discount code in form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
Labels: ready to review

#1649 style: upcoming-events-about-page
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
Labels: ready to merge

#1650 feat: add check for script and javascript in pdf file
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.ts
Labels: ready to review

#1648 feat: add min and max users count in discount code for payment
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupon-form/discount-coupon-form.component.ts
  libs/shared/models/src/lib/discount-code.model.ts
Labels: ready to review

#1651 fix: upload resume
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.ts
Labels: ready to merge

#1653 refactor: collapse event dashboard
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/shared-components/sidebar/enum/sidebar.enum.ts
  apps/shared-components/sidebar/sidebar.component.scss
Labels: ready to merge

#1652 fix: job schema
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list-card/job-list-card.component.ts
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/shared-models/job.model.ts
Labels: ready to merge

#1654 style: hackathons homepage schema
  apps/commudle-admin/src/app/feature-modules/public-community/components/public-community-hackathons/public-community-hackathons.component.ts
Labels: ready to merge

#1655 fix: show error if designation max word limit exceed
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
Labels: ready to review

#1656 refactor: resume preview open in same tab
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume-card/user-resume-card.component.html
Labels: ready to review

#1636 refactor: dashboard
  apps/commudle-admin/src/app/app-shared-components/event-hackathon-registrations/event-hackathon-registrations.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.ts
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/dashboard/dashboard.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-card/labs-card.component.ts
  apps/shared-directives/activity-feed.directive.ts
  apps/shared-directives/shared-directives.module.ts
  apps/shared-services/user-engagement-records.service.ts
  libs/shared/environments/src/lib/environments.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: changes requested

#1657 style: add schema data for newsletter list
  apps/commudle-admin/src/app/feature-modules/public-newsletters/components/newsletter-list/newsletter-list.component.ts
Labels: ready to merge

#1662 style: add schema data for community newsletter
  apps/commudle-admin/src/app/feature-modules/public-community/components/newsletters/newsletter/newsletter.component.ts
Labels: ready to merge

#1660 style: add schema data for main-newsletter
  apps/commudle-admin/src/app/feature-modules/main-newsletters/components/main-newsletter/main-newsletter.component.ts
Labels: ready to merge

#1659 fix: faq schema data
  apps/commudle-admin/src/app/feature-modules/expert-program/components/experts-program/experts-program.component.html
  apps/commudle-admin/src/app/feature-modules/expert-program/components/experts-program/experts-program.component.ts
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.html
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.ts
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.ts
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.html
  apps/commudle-admin/src/app/feature-modules/public-book-page/components/book-page/book-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.html
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.ts
  libs/shared/components/src/lib/components/faq/faq-card/faq-card.component.html
  libs/shared/components/src/lib/components/faq/faq-card/faq-card.component.scss
  libs/shared/components/src/lib/components/faq/faq-card/faq-card.component.spec.ts
  libs/shared/components/src/lib/components/faq/faq-card/faq-card.component.ts
  libs/shared/components/src/lib/components/faq/faq.component.html
  libs/shared/components/src/lib/components/faq/faq.component.scss
  libs/shared/components/src/lib/components/faq/faq.component.ts
  libs/shared/components/src/lib/components/public-faqs/public-faqs.component.html
  libs/shared/components/src/lib/components/public-faqs/public-faqs.component.scss
  libs/shared/components/src/lib/components/public-faqs/public-faqs.component.spec.ts
  libs/shared/components/src/lib/components/public-faqs/public-faqs.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/models/src/lib/faq.model.ts
Labels: ready to merge

#1661 refactor: add testing in pull request template
  pull_request_template.md
Labels: ready to merge

#1663 fix: clone event
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-actions/community-events-list-actions.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
Labels: ready to merge, backend-changes

#1665 style: font style of testimonial card
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
  apps/shared-services/cms.service.ts
Labels: ready to merge

#1664 style: add schema data for job
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
Labels: ready to merge

#1666 feat: add checkbox for approval based payments
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-models/data_form_entity.model.ts
  apps/shared-models/enums/registration_statuses.enum.ts
  apps/shared-models/event_data_form_enity_group.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/event-ticket-order.service.ts
Labels: work in progress

#1667 style: collapse hackathon dashboard
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.ts
Labels: ready to merge

#1669 feat: add checkbox for approval based payments
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
  apps/shared-models/data_form_entity.model.ts
  apps/shared-models/enums/registration_statuses.enum.ts
  apps/shared-models/event_data_form_enity_group.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/event-ticket-order.service.ts
Labels: ready to merge

#1672 Events approval based tickets
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.ts
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.html
  libs/shared/models/src/lib/db-models.enum.ts
Labels: ready to merge

#1668 style: collapse orgs page sidebar
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/shared-components/sidebar/sidebar.component.html
Labels: ready to merge
