Repository commudle/commudle-ng, pull requests merged in 2024-07, with the labels that each got.

#1429 fix: max-width in banner image
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.scss
  apps/shared-components/banner-image/banner-image.component.scss
Labels: ready to merge

#1431 refactor: open initial sidebar for channel
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
Labels: ready to review

#1384 refactor: personal chat interface
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.scss
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-window/chats-window.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-window/chats-window.component.scss
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-window/chats-window.component.ts
  apps/shared-components/discussion-personal-chat/discussion-personal-chat.component.html
  apps/shared-components/discussion-personal-chat/discussion-personal-chat.component.scss
  apps/shared-components/discussion-personal-chat/discussion-personal-chat.component.ts
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/messages/messages-list/message/message.component.scss
  apps/shared-components/messages/messages-list/message/message.component.ts
  apps/shared-components/messages/messages-list/messages-list.component.scss
  apps/shared-components/user-live-status/user-live-status.component.html
  apps/shared-components/user-live-status/user-live-status.component.scss
  apps/shared-components/user-live-status/user-live-status.component.ts
  apps/shared-components/user-profile-mini/user-profile-mini.component.html
  apps/shared-components/user-profile-mini/user-profile-mini.component.scss
  apps/shared-components/user-profile-mini/user-profile-mini.component.ts
  apps/shared-components/votes-display/votes-display.component.ts
Labels: ready to review

#1433 refactor: personal chat interface
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/messages/messages-list/message/message.component.scss
Labels: work in progress

#1434 fix: hackathon dates and teammate
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.html
Labels: ready to review

#1437 style: help-section-gtm
  apps/commudle-admin/src/app/app-shared-components/help-section/help-section.component.ts
Labels: ready to merge

#1438 feat: schema data for testimonials
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.ts
Labels: ready to review

#1439 fix: auth for no login user [Hackathon page]
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.ts
Labels: ready to review

#1440 style: change title and meta of case studies and communities
  apps/commudle-admin/src/app/components/communities/communities-list/communities-list.component.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.ts
Labels: ready to merge

#1441 style: change form id in pricing
  apps/commudle-admin/src/app/feature-modules/features/components/features/features.component.ts
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/public-agencies/components/aggencies/aggencies.component.html
Labels: ready to merge

#1435 feat: add event type for events
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
  libs/shared/models/src/lib/event.model.ts
Labels: ready to review, backend-changes

#1444 feat: add acceptance_mail_sent in hackathon team acceptance
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  libs/shared/models/src/lib/hackathon-team.model.ts
Labels: ready to review, backend-changes

#1436 fix: agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-embedded-video-stream/event-embedded-video-stream.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-track-slots/user-track-slots.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page.component.ts
  apps/commudle-admin/src/app/services/event-location-tracks.service.ts
  apps/commudle-admin/src/app/services/event-locations.service.ts
  apps/commudle-admin/src/app/services/track_slots.service.ts
  apps/shared-models/event-location-track.model.ts
  apps/shared-models/event-location.model.ts
  apps/shared-models/locations.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1443 fix: public side agenda
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/services/event-locations.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: work in progress

#1448 style: hackathon build chip
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  libs/shared/models/src/lib/hackathon-team.model.ts
Labels: work in progress

#1446 feat: notes ui in user response detail
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  libs/shared/models/src/lib/note.model.ts
Labels: ready to review

#1447 fix: reply for close discussion
  apps/shared-components/messages/messages-list/messages-list.component.html
  apps/shared-components/messages/messages-list/messages-list.component.ts
  apps/shared-components/messages/messages.component.html
Labels: ready to review

#1449 fix: agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
Labels: ready to merge

#1453 fix: apply now button in hackathon public page
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.html
Labels: ready to review

#1454 feat: add login to apply for hackathon
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
Labels: ready to review

#1452 feat: add multi date on upcoming event card
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
Labels: ready to review

#1451 style: add youtube link to footer
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.scss
  apps/commudle-admin/src/app/components/footer/footer.component.ts
Labels: ready to merge

#1456 fix: agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/services/track_slots.service.ts
Labels: ready to merge

#1457 style: public side agenda
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.ts
  apps/commudle-admin/src/app/services/event-locations.service.ts
Labels: ready to review

#1455 style: public hackathon schema
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
Labels: ready to merge

#1458 refactor: update rzp_live keys
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.scss
  apps/shared-components/user-details-form/user-details-form.component.html
  apps/shared-components/user-details-form/user-details-form.component.ts
  libs/shared/environments/src/lib/environments.ts
Labels: ready to review

#1461 fix: agenda multiple api calls
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
Labels: ready to merge

#1462 style: upcoming-events-count events
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  libs/shared/models/src/lib/community.model.ts
Labels: ready to merge

#1463 style: public side
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
Labels: ready to merge

#1464 style: tags in public page agenda
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
Labels: ready to review

#1465 style: tags on admin side
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
Labels: ready to review

#1469 fix: admin agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/shared-components/badge/badge.component.html
  apps/shared-components/badge/badge.component.scss
Labels: changes requested

#1470 feat: edit for details
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.ts
  apps/shared-components/user-details-checkbox-form/user-details-checkbox-form.component.ts
  apps/shared-models/event_data_form_enity_group.model.ts
Labels: ready to review

#1468 style: builds hackathon badge
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.ts
  apps/shared-components/badge/badge.component.html
  apps/shared-components/badge/badge.component.scss
Labels: ready to merge

#1471 feat: add checkbox for Allow Multi Person Ticket
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.ts
  libs/shared/models/src/lib/payment-detail.model.ts
Labels: ready to review, backend-changes

#1477 style: events page horizontal scroll and padding in mobile view
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to merge

#1478 fix: about_me replace for empty about_me
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
Labels: ready to review

#1481 fix: image alignment issue in builds
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
Labels: ready to merge

#1472 Fix: agenda
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/track-slot-form/track-slot-form.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.ts
  apps/shared-components/badge/badge.component.html
  apps/shared-components/badge/badge.component.scss
Labels: ready to merge

#1479 feat: show description button with view more and hide one submit butt…
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.ts
Labels: ready to review

#1480 feat: show project submit details in application review list of hacka…
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
Labels: ready to review
