Repository commudle/commudle-ng, pull requests merged in 2024-05, with the labels that each got.

#1323 fix: loading when sending speaker CSV
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members-list/community-members-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-members-list/community-members-list.component.ts
Labels: ready to review

#1322 fix: badge image aspect
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-assign/admin-badges-assign.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-badges/admin-badges-list/admin-badges-list.component.scss
Labels: ready to review

#1321 feat: what new
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new-card/whats-new-card.component.html
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new-card/whats-new-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new-card/whats-new-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new-card/whats-new-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.html
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.scss
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.ts
  apps/commudle-admin/src/app/app.component.html
  apps/shared-models/whats-new.model.ts
  apps/shared-services/whats-new.service.ts
Labels: ready to merge

#1328 style: add text color and font sizes to tinyMce
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
Labels: ready to merge

#1327 refactor: remove query from url canonical
  libs/shared/services/src/lib/seo.service.ts
Labels: ready to merge

#1329 Refactor newsletter
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.html
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.scss
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/shared-models/newsletter.model.ts
Labels: ready to review

#1333 fix: button color while unjoined community
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.scss
Labels: ready to review

#1332 refactor: add back button in create event page
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.scss
Labels: ready to review

#1331 Fix-community-admin
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
Labels: ready to review

#1330 feat: featured item for user experts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities-channels/admin-featured-communities-channels.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-communities/admin-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-events/admin-featured-events.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-labs/admin-featured-labs.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured-users/admin-featured-users.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/admin-featured.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/create-featured-item/create-featured-item.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-featured/featured-community-builds/featured-community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/shared-models/featured-items.model.ts
  libs/shared/models/src/lib/db-models.enum.ts
Labels: ready to review

#1336 fix: loader while payment
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.ts
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.scss
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.ts
  apps/shared-components/shared-components.module.ts
Labels: ready to review

#1334 fix: loader in create event
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.ts
Labels: ready to review

#1340 fix: order of edfeg
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.scss
Labels: ready to review

#1221 refactor: experts page
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.ts
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-featured/experts-featured.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-featured/experts-featured.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-featured/experts-featured.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-featured/experts-featured.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-header/experts-header.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-header/experts-header.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-header/experts-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-header/experts-header.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/public-home-list-experts-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/public-home-list-experts.module.ts
  apps/commudle-admin/src/app/services/experts.service.ts
  apps/commudle-admin/src/app/services/featured-items.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: work in progress

#1341 refactor: experts page
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-featured/experts-featured.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/public-home-list-experts.module.ts
  apps/commudle-admin/src/app/services/experts.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1345 fix: css styling of colors
  apps/commudle-admin/src/app/feature-modules/public-reading-book/components/reading-book/reading-book.component.scss
Labels: ready to merge

#1342 fix: message component user name dark mode
  libs/shared/components/src/lib/components/discussion/message/message.component.scss
Labels: ready to merge

#1343 fix: remove structured schema
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
Labels: ready to merge

#1344 fix: sponsors url bug on public-events page
  apps/commudle-admin/src/app/feature-modules/public-events/components/sponsors/sponsors.component.html
Labels: ready to merge

#1347 fix: pan card and IFSC code in capital
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.scss
Labels: ready to review

#1346 refactor: new updates events
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/about/about.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  libs/shared/models/src/lib/community.model.ts
Labels: ready to merge

#1351 fix: pan info required/not required with business types
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.ts
Labels: ready to review

#1349 refactor: add razorpay api key for production
  libs/shared/environments/src/lib/environments.ts
Labels: ready to review, hold

#1355 style: connect account form
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.ts
  apps/shared-components/alert/alert.component.html
  apps/shared-components/alert/alert.component.scss
  apps/shared-components/alert/alert.component.ts
Labels: ready to review

#1357 fix: date and time in edit event
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
Labels: ready to review

#1360 refactor: sidebar for help section
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.ts
  apps/commudle-admin/src/app/services/sidebar.service.ts
  apps/shared-components/sidebar/enum/sidebar.enum.ts
  apps/shared-components/sidebar/service/sidebar.service.ts
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.ts
Labels: ready to review

#1359 fix: switch between newsletter for editor
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.html
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.ts
Labels: ready to review

#1361 fix: whats new popup
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.scss
  apps/commudle-admin/src/app/app-shared-components/whats-new/whats-new.component.ts
  apps/shared-services/whats-new.service.ts
Labels: ready to merge

#1354 refactor: case study
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.html
  apps/commudle-admin/src/app/app-shared-components/testimonial-card/testimonial-card.component.ts
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/case-study-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/case-study/case-study.module.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies-header/case-studies-header.component.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-studies/case-studies.component.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-card/case-study-card.component.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-header/case-study-header.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-header/case-study-header.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-header/case-study-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study-header/case-study-header.component.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.html
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.scss
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/shared-models/case-study.model.ts
  apps/shared-models/testimonial.model.ts
Labels: work in progress

#1362 fix: hackathon prizes for 0
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details-mini-card/public-hackathon-details-mini-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-prizes/public-hackathon-prizes.component.html
Labels: ready to review

#1363 feat: cms enum
  apps/shared-models/enums/cms.enum.ts
Labels: ready to review

#1364 refactor: add event start and end date for multiple date event
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events-card/homepage-events-card.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events-card/homepage-events-card.component.scss
Labels: ready to review

#1352 refactor: fix channel function name in service
  apps/commudle-admin/src/app/feature-modules/community-channels/community-channels.module.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-forum-dashboard/channel-forum-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/edit-channel/edit-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/edit-channel/edit-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/invite-form/invite-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/invite-form/invite-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-form/community-channel-form.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel-list/community-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-channel-list/community-channels-dashboard-channel-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard-forum-list/community-channels-dashboard-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channels-dashboard/community-channels-dashboard.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-list/community-forum-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum/community-forum.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-list/community-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/email-join/email-join.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/join-by-token/join-by-token.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/new-community-channel/new-community-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/new-community-channel/new-community-channel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/new-community-channel/new-community-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-channels-and-forums/community-channels-and-forums.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/Resolver/community-group-details.resolver.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/community-groups.module.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/community-group-channel/community-group-channel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/community-channels-list/community-channels-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/community-channels-list/community-channels-list.component.ts
  libs/shared/environments/src/lib/environments.ts
  libs/shared/models/src/index.ts
  libs/shared/models/src/lib/community-channel.model.ts
  libs/shared/models/src/lib/community-group.model.ts
  libs/shared/models/src/lib/hackathon.model.ts
  libs/shared/services/src/lib/community-channel-manager.service.ts
  libs/shared/services/src/lib/community-channels.service.ts
Labels: ready to review

#1366 fix: case study testimonials
  apps/commudle-admin/src/app/feature-modules/case-study/components/case-study/case-study.component.html
Labels: ready to merge

#1367 refactor: add hackathons and case studies in sitemap
  apps/commudle-admin/src/sitemap.xml
Labels: ready to review

#1370 fix: dark mode blog page
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
Labels: work in progress

#1374 style: lab created text
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.html
Labels: ready to merge

#1376 style: add fragments to builds
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-projects/featured-projects.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
Labels: ready to merge

#1377 feat: hackathon consent while filing registration form
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-hackathon-judge-invite/accept-hackathon-judge-invite.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/accept-hackathon-teammate-invite/accept-hackathon-teammate-invite.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/hackathon-registration-consent/hackathon-registration-consent.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/hackathon-registration-consent/hackathon-registration-consent.component.scss
  apps/commudle-admin/src/app/app-shared-components/user-consents/hackathon-registration-consent/hackathon-registration-consent.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/user-consents/hackathon-registration-consent/hackathon-registration-consent.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-consents/user-consents.component.html
  apps/commudle-admin/src/app/app-shared-components/user-consents/user-consents.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/shared-models/enums/consent-types.enum.ts
Labels: ready to review
