Repository commudle/commudle-ng, pull requests merged in 2025-04, with the labels that each got.

#1825 style: add status popup confirmation on completed status
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.ts
Labels: ready to merge

#1816 feat: hackathon stats
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.html
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.scss
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.routing.ts
  apps/commudle-admin/src/app/services/stats/hackathons.service.ts
  apps/commudle-admin/src/app/services/stats/stats-labs.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review, work in progress, backend-changes

#1826 fix: image type validation
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/sponsors/sponsors.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-sponsor/hackathon-control-panel-sponsor.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-updates/hackathon-control-panel-updates.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
Labels: ready to review

#1830 fix: multiple user bug chats container
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.ts
Labels: ready to merge

#1831 fix: user profile bugs
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-lab-card/user-lab-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-lab-card/user-lab-card.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social-card/user-social-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social-card/user-social-card.component.scss
Labels: ready to merge

#1828 fix: undefined create_at sanity bug on user chat
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
Labels: ready to merge

#1829 feat: add user views over time chart to hackathon stats
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.ts
  apps/commudle-admin/src/app/services/stats/hackathons.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1833 fix: update order creation parameters in Razorpay service call
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
Labels: ready to merge

#1834 style: add tooltip to organizer
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-community-card/user-community-card.component.html
Labels: ready to merge

#1827 style: navbar in logged out user
  apps/commudle-admin/src/app/app.component.html
  apps/commudle-admin/src/app/app.component.scss
  apps/commudle-admin/src/app/app.component.ts
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
  apps/commudle-admin/src/app/components/navbar/navbar.component.html
  apps/commudle-admin/src/app/components/navbar/navbar.component.scss
  apps/commudle-admin/src/app/components/navbar/navbar.component.ts
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.html
Labels: ready to merge

#1832 refactor(styles): remove margin from header image in campaign assets display
  apps/commudle-admin/src/app/feature-modules/notifications/components/user-notifications-campaign/user-notifications-campaign.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile-campaign/public-profile-campaign.component.scss
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.scss
Labels: ready to review

#1838 fix: user profile cards on route change
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.ts
Labels: ready to merge

#1842 fix: campaigns
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/shared-components/campaign-list/campaign-list.component.html
  apps/shared-components/campaign-list/campaign-list.component.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/campaign.service.ts
Labels: ready to merge

#1835 refactor: update API routes for hackathon statistics endpoints
  apps/commudle-admin/src/app/services/stats/hackathons.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to merge

#1836 feat(analytics): integrate Google Tag Manager for click and view in campaign
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.html
  apps/shared-components/campaign-list/campaign-list.component.ts
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
Labels: ready to merge

#1846 fix(hackathon-card): ensure prize money displays only when amount
  apps/shared-components/hackathon-cards/hackathon-large-card/hackathon-large-card.component.html
Labels: ready to review

#1845 fix: event collabration
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/collaboration-community/collaboration-community.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/collaboration-community/collaboration-community.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.ts
  apps/commudle-admin/src/app/services/event-collaboration-communities.service.ts
  apps/shared-models/event_collaboration_community.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1844 style: sidebar scroll fixes and hides on click outside
  apps/commudle-admin/src/app/app.component.html
  apps/commudle-admin/src/app/app.component.scss
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
  apps/shared-components/sidebar/sidebar.component.ts
Labels: ready to merge

#1849 feat: add visual indication for rejected collaborations
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
Labels: ready to review

#1850 fix: comment out unused animation loading logic in homepage component
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
Labels: ready to review

#1847 refactor: builds listing page
  apps/commudle-admin/src/app/app-shared-components/featured-builds/featured-builds.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-builds/featured-builds.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-builds/featured-builds.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/featured-builds/featured-builds.component.ts
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.scss
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/community-builds.module.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.ts
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to review

#1851 fix(hackathon): rename review route to applications-dashboard, fix search
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.routing.ts
Labels: ready to merge

#1848 fix: update campaign type checks
  apps/commudle-admin/src/app/feature-modules/admin-campaign/admin-campaign.module.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.html
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.ts
  apps/shared-components/campaign-list/campaign-list.component.ts
  apps/shared-components/campaign-stats/campaign-stats.component.html
  apps/shared-components/campaign-stats/campaign-stats.component.ts
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.html
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
  libs/shared/models/src/lib/campaign-stats.model.ts
  libs/shared/models/src/lib/campaign.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/campaign.service.ts
Labels: work in progress

#1854 fix: show team details in stats for team participation
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-stats/hackathon-control-panel-stats.component.ts
Labels: ready to review

#1853 style(collaborating-communities): add rounded corners to event collaboration community cards
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
Labels: ready to review

#1837 feat: add filter in HUR
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-individual-team-email/hackathon-individual-team-email.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-individual-team-email/hackathon-individual-team-email.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-individual-team-email/hackathon-individual-team-email.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-individual-team-email/hackathon-individual-team-email.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-track-card/hackathon-track-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-user-dashboard/public-hackathon-user-dashboard.component.ts
  apps/commudle-admin/src/app/services/hackathon-user-responses.service.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
  libs/shared/models/src/lib/hackathon-prize.model.ts
  libs/shared/models/src/lib/hackathon-user-response.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/emailer-preview.service.ts
Labels: ready to review

#1852 fix: builds listing page fixes
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-top-builders/builds-top-builders.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.scss
  libs/shared/models/src/lib/community-build.model.ts
Labels: ready to merge, backend-changes

#1855 fix: add default image URL binding for campaign assets display across components
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/notifications/components/user-notifications-campaign/user-notifications-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/notifications/components/user-notifications-campaign/user-notifications-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-page-campaign/search-page-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-page-campaign/search-page-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile-campaign/public-profile-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile-campaign/public-profile-campaign.component.ts
  apps/shared-components/campaign-list/campaign-list.component.html
  apps/shared-components/campaign-list/campaign-list.component.scss
  apps/shared-components/campaign-list/campaign-list.component.ts
Labels: ready to review

#1857 fix: add conditional rendering for thumbnail image in build card
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.html
Labels: ready to merge

#1858 style: eye icon in builds page and tooltip in profile
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-upcoming/public-home-list-speakers-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-community-card/user-community-card.component.html
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#1861 fix: enhance user engagement tracking for default image interactions
  apps/shared-components/campaign-list/campaign-list.component.html
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
Labels: ready to review
