Repository commudle/commudle-ng, pull requests merged in 2025-03, with the labels that each got.

#1779 feat: lsit of purchase orders
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds-header/builds-header.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/admin-campaigns.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  libs/shared/components/src/index.ts
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.html
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.scss
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.spec.ts
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/models/src/lib/purchase-order.model.ts
  libs/shared/models/src/lib/razorpay-order.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/campaign.service.ts
  libs/shared/services/src/lib/purchase-order.service.ts
Labels: ready to merge

#1780 feat: implement infinite scroll for channel members list
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.scss
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-channel/community-channel.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/community-forum-message/community-forum-message.component.html
Labels: ready to review

#1778 feat: hackathon filter and seach for user registration
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
Labels: ready to review, backend-changes

#1782 fix: labs search infinite scroll
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.ts
Labels: ready to merge

#1784 fix: gap above events page
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to merge

#1781 refactor: events listing page
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/listing-pages-layout/listing-pages-layout.component.scss
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.html
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-activity/community-group-activity.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/membership-toggle/membership-toggle.component.scss
  apps/shared-components/badge/badge.component.scss
  apps/shared-components/community-badge/community-badge.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.ts
  apps/shared-modules/mini-user-profile/components/user-follow/user-follow.component.html
Labels: ready to merge

#1783 fix: update label for account holder name in community bank details
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
Labels: ready to review

#1788 fix: handle optional header image in lab component
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.ts
Labels: ready to review

#1789 feat: implement user consent handling in data form submission
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form.component.ts
  apps/shared-components/data-form-fill/data-form-fill.component.html
  apps/shared-components/data-form-fill/data-form-fill.component.ts
  apps/shared-components/user-details-form/user-details-form.component.ts
  libs/shared/services/src/lib/toastr.service.ts
Labels: ready to review

#1791 style: event horizontal card bug
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.scss
  apps/shared-components/community-badge/community-badge.component.scss
Labels: ready to review

#1790 feat: add search functionality for channel members and admins
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-members/channel-members.component.ts
  libs/shared/services/src/lib/community-channels.service.ts
Labels: ready to review

#1786 Fix: hackathons
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/events/events.module.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-contact-details-form/hackathon-control-panel-contact-details-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-contact-details-form/hackathon-control-panel-contact-details-form.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-contact-details-form/hackathon-control-panel-contact-details-form.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dates-form/hackathon-control-panel-dates-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dates-form/hackathon-control-panel-dates-form.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dates-form/hackathon-control-panel-dates-form.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-tracks-prizes.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-tracks-prizes.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-tracks-prizes.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-project-details-form/public-hackathon-project-details-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-project-details-form/public-hackathon-project-details-form.component.ts
  apps/shared-components/edit-data-form/edit-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/next-step-card/next-step-card.component.html
  apps/shared-components/next-step-card/next-step-card.component.scss
  apps/shared-components/next-step-card/next-step-card.component.spec.ts
  apps/shared-components/next-step-card/next-step-card.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-models/hackathon.model.ts
  libs/shared/services/src/lib/help-dictionary.store.ts
Labels: ready to review

#1795 fix: event dates timezone display
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
Labels: ready to merge

#1794 Fix Hackatthob
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-round-card/hackathon-control-panel-round-card.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-sponsor/hackathon-control-panel-sponsor-card/hackathon-control-panel-sponsor-card.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-sponsor/hackathon-control-panel-sponsor.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-sponsor/hackathon-control-panel-sponsor.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-sponsor/hackathon-control-panel-sponsor.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-control-panel-prize.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-control-panel-prize.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-control-panel-prize.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-control-panel-track.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-control-panel-track.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-control-panel-track.component.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
  apps/shared-components/faq-control-panel/faq-control-panel.component.html
  apps/shared-components/faq-control-panel/faq-control-panel.component.ts
  apps/shared-models/hackathon-sponsor.ts
Labels: ready to review

#1798 refactor: preview email
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/services/emails.service.ts
  libs/shared/services/src/index.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/emailer-preview.service.ts
Labels: ready to merge

#1797 feat: implement image upload functionality for custom pages
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.ts
  apps/commudle-admin/src/app/feature-modules/main-newsletters/services/main-newsletters.service.ts
  apps/commudle-admin/src/app/services/custom-page.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1796 feat: enhance payment error handling with user confirmation
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
Labels: ready to review

#1785 fix: page scroll community admin sidebar
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
Labels: work in progress

#1802 style: sanity content color of listing page
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.html
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.scss
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.ts
Labels: ready to merge

#1800 feat: Sponsors list with group by in public hackathon page
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/public-hackathon.module.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
Labels: ready to review

#1801 fix: image attachment function by adding parent for permissions
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.ts
  apps/commudle-admin/src/app/services/custom-page.service.ts
Labels: ready to review

#1803 fix: preview email fixes
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
  libs/shared/services/src/lib/emailer-preview.service.ts
Labels: ready to review

#1804 fix: email preview bugs
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/event-form-responses.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.scss
Labels: ready to review

#1805 refactor: add discount code to form submission
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
Labels: ready to review

#1806 fix: ensure promo code is reset only when present
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
Labels: ready to review

#1807 fix: emailer component button styling
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
Labels: ready to merge

#1810 style: emailer preview template in mobile
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
Labels: ready to merge

#1813 fix: email preview dark mode
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
Labels: ready to merge

#1814 fix: email preview
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.ts
Labels: ready to merge

#1808 refactor: revamp hackathon emails
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.html
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.scss
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-control-panel-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-overall-round-selection-update-email/hackathon-overall-round-selection-update-email.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-round-general-mailer/hackathon-round-general-mailer.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-status-filter-general-emails/hackathon-status-filter-general-emails.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-status-filter-general-emails/hackathon-status-filter-general-emails.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-status-filter-general-emails/hackathon-status-filter-general-emails.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-winner-announcement-emailer/hackathon-winner-announcement-emailer.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-winner-announcement-emailer/hackathon-winner-announcement-emailer.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-emails/hackathon-winner-announcement-emailer/hackathon-winner-announcement-emailer.component.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/emailer-preview.service.ts
Labels: ready to merge

#1809 style: update button and prize display layout in hackathon control panel
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.html
  apps/commudle-admin/src/app/app-shared-components/admin-hackathon/admin-hackathon.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/admin-community-hackathon/admin-community-hackathon.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-registrations/hackathon-control-panel-registrations.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-control-panel-prize.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-control-panel-track.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-track-card/hackathon-track-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-track/hackathon-track-card/hackathon-track-card.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-tracks-prizes.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-new-form/hackathon-new-form.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  libs/shared/models/src/lib/hackathon-user-response.model.ts
Labels: ready to review, backend-changes

#1736 fix: update Lottie animation path to local asset
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
Labels: ready to review

#1815 feat: add URL validation for social media fields in user details form
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.ts
  apps/shared-components/user-details-form/user-details-form.component.html
  apps/shared-components/user-details-form/user-details-form.component.ts
Labels: ready to review

#1817 style: toggle end date in work history
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history.component.ts
Labels: ready to merge

#1819 fix: community build description '&' bug
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
Labels: ready to merge

#1818 fix: update entry pass and emit registration status on successful update
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.ts
Labels: ready to review, backend-changes

#1820 refactor: replace hardcoded S3 URLs with constants from AwsS3Bucket
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.ts
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to review

#1821 fix: community Builds teammates
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build.component.html
Labels: ready to review

#1824 fix: prevent loading animation for bots in homepage component
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage/homepage.component.ts
Labels: ready to merge

#1823 fix: email template header scroll
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.html
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.scss
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.ts
Labels: ready to merge

#1822 feat: add confirmation dialog for changing registration for entry pass
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.ts
Labels: ready to review
