Repository commudle/commudle-ng, pull requests merged in 2025-05, with the labels that each got.

#1859 refactor: experts listing page
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.html
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/tech-sessions-card/tech-sessions-card.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts-users/experts-users.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/experts/experts.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-content/public-home-list-speakers-content.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.ts
  libs/shared/models/src/lib/badge.model.ts
  libs/shared/models/src/lib/user.model.ts
Labels: ready to merge, backend-changes

#1863 fix: experts listing page bug fixes
  apps/commudle-admin/src/app/app-shared-components/event-content-card/event-content-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
Labels: ready to merge

#1862 refactor: replace expert tick across all pages
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-experts-card/featured-experts-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.html
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/top-builders-card/top-builders-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/user-expert-tick.component.html
  apps/commudle-admin/src/app/app-shared-components/user-expert-tick.component.scss
  apps/commudle-admin/src/app/app-shared-components/user-expert-tick.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/user-expert-tick.component.ts
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.html
  apps/commudle-admin/src/app/components/home/components/home-experts/home-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-features/homepage-features.component.html
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-features/homepage-features.component.scss
  apps/commudle-admin/src/app/feature-modules/homepage/homepage.module.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab-discussion/lab-discussion-message/lab-discussion-message.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/public-community.module.ts
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.scss
  apps/commudle-admin/src/app/feature-modules/search/search.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.scss
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  apps/shared-components/discussion-personal-chat/user-personal-chat-message/user-personal-chat-message.component.html
  apps/shared-components/discussion-personal-chat/user-personal-chat-message/user-personal-chat-message.component.scss
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/messages/messages-list/message/message.component.scss
  apps/shared-components/qna/qna-list/qna-list-item/qna-list-item.component.html
  apps/shared-components/qna/qna-list/qna-list-item/qna-list-item.component.scss
  apps/shared-components/shared-components.module.ts
  apps/shared-components/user-profile-mini/user-profile-mini.component.html
  apps/shared-components/user-profile-mini/user-profile-mini.component.scss
  apps/shared-modules/mention/components/entity-profile/entity-profile.component.html
  apps/shared-modules/mention/components/entity-profile/entity-profile.component.scss
  apps/shared-modules/mention/mention.module.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-medium/user-profile-card-medium.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-medium/user-profile-card-medium.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-small/user-profile-card-small.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-small/user-profile-card-small.component.scss
  apps/shared-modules/mini-user-profile/mini-user-profile.module.ts
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.scss
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.html
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.scss
  libs/shared/components/src/lib/components/discussion/message/message.component.html
  libs/shared/components/src/lib/components/discussion/message/message.component.scss
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.html
  libs/shared/components/src/lib/components/user-profile/user-profile-mini-card/user-profile-mini-card.component.scss
  libs/shared/components/src/lib/shared-components.module.ts
Labels: ready to merge

#1866 fix: messages replies mention on events page
  apps/shared-components/messages/messages-list/message/message.component.html
  apps/shared-components/messages/messages-list/message/message.component.ts
Labels: ready to merge

#1864 feat: add hackathon email stats and overall stats components with routing and service integration
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-email-stats/hackathon-control-panel-email-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-email-stats/hackathon-control-panel-email-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-email-stats/hackathon-control-panel-email-stats.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-email-stats/hackathon-control-panel-email-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-overall-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-overall-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-overall-stats.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-overall-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/hackathon-control-panel.routing.ts
  apps/commudle-admin/src/app/services/stats/hackathons.service.ts
  apps/shared-models/fixed-email.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review, backend-changes

#1869 fix: tag component input in dark mode
  apps/shared-components/tag/tag.component.scss
Labels: ready to merge

#1867 feat: add team switcher for hackathon user responses
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.scss
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/commudle-admin/src/app/services/hackathon-user-responses.service.ts
  libs/shared/models/src/lib/hackathon-user-response.model.ts
Labels: ready to review, backend-changes

#1860 feat: add functionality to send application status emails with previews
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-overall-stats/hackathon-control-panel-stats/hackathon-control-panel-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.html
  apps/commudle-admin/src/app/services/hackathon.service.ts
  apps/commudle-admin/src/app/services/stats/hackathons.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/emailer-preview.service.ts
Labels: ready to review, backend-changes

#1871 feat: implement SEO handling for community builds with noIndex logic
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build.component.ts
Labels: ready to review

#1870 fix: builds thumbnail images accross website
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-build-card/community-build-card.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-build-card/user-build-card.component.html
  apps/shared-components/build-card/build-card.component.html
Labels: ready to review

#1873 hot fix: add UserExpertTick component with template, styles, and tests
  libs/shared/components/src/lib/components/user/user-expert-tick/user-expert-tick.component.html
  libs/shared/components/src/lib/components/user/user-expert-tick/user-expert-tick.component.scss
  libs/shared/components/src/lib/components/user/user-expert-tick/user-expert-tick.component.spec.ts
  libs/shared/components/src/lib/components/user/user-expert-tick/user-expert-tick.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
Labels: ready to merge

#1874 refactor: remove featured section tags selected
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
Labels: ready to merge

#1875 fix: add overflow hidden to footer grid for better layout
  apps/commudle-admin/src/app/components/footer/footer.component.html
Labels: ready to review

#1877 fix: enhance user engagement tracking for campaign and default images
  apps/commudle-admin/src/app/feature-modules/admin-campaign/admin-campaign.routing.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/admin-campaigns-list/admin-campaigns-list.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/sys-admin-campaign-stats/sys-admin-campaign-stats.component.ts
  apps/shared-components/campaign-list/campaign-list.component.html
  apps/shared-components/campaign-stats/campaign-stats.component.html
  apps/shared-components/campaign-stats/campaign-stats.component.ts
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.scss
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
Labels: help wanted, ready to review

#1878 fix: implement SEO service integration across campaign components
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-dashboard/campaign-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form.component.ts
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/admin-campaigns-list/admin-campaigns-list.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-purchase-orders/campaign-purchase-orders.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/sys-admin-campaign-stats/sys-admin-campaign-stats.component.ts
  apps/shared-components/campaign-details/campaign-details.component.html
  apps/shared-components/campaign-details/campaign-details.component.scss
  apps/shared-components/campaign-details/campaign-details.component.ts
  apps/shared-components/campaign-stats/campaign-stats.component.ts
Labels: ready to review

#1879 refactor: user sidebar and user account profile details
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app.module.ts
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
  apps/commudle-admin/src/app/components/navbar-user-context-menu/navbar-user-context-menu.component.html
  apps/commudle-admin/src/app/components/navbar-user-context-menu/navbar-user-context-menu.component.scss
  apps/commudle-admin/src/app/components/navbar-user-context-menu/navbar-user-context-menu.component.spec.ts
  apps/commudle-admin/src/app/components/navbar-user-context-menu/navbar-user-context-menu.component.ts
  apps/commudle-admin/src/app/components/navbar/navbar.component.html
  apps/commudle-admin/src/app/components/navbar/navbar.component.scss
  apps/commudle-admin/src/app/components/navbar/navbar.component.ts
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.html
  apps/commudle-admin/src/app/components/sidebar-menu/sidebar-menu.component.scss
  apps/commudle-admin/src/app/components/user-account-menu/user-account-menu.component.html
  apps/commudle-admin/src/app/components/user-account-menu/user-account-menu.component.scss
  apps/commudle-admin/src/app/components/user-account-menu/user-account-menu.component.spec.ts
  apps/commudle-admin/src/app/components/user-account-menu/user-account-menu.component.ts
Labels: ready to review

#1868 refactor: speakers listing page
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.html
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-upcoming/public-home-list-speakers-upcoming.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-upcoming/public-home-list-speakers-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/public-home-list-speakers.module.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.ts
  libs/shared/models/src/lib/user.model.ts
Labels: ready to review

#1880 style: fix custom pgae meta data of orgs and community
  apps/commudle-admin/src/app/feature-modules/public-community-groups/components/community-group-custom-page/community-group-custom-page.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/custom-page/custom-page.component.ts
Labels: ready to merge

#1882 feat: discount codes in campaign orrr product pricing
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/discount-coupons/discount-coupons.component.ts
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.html
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.scss
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.ts
  apps/commudle-admin/src/app/feature-modules/payment-checkout/payment-checkout.module.ts
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.html
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.scss
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-controls/community-controls.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-controls/community-controls.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/purchase-orders/purchase-orders.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/purchase-orders/purchase-orders.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/purchase-orders/purchase-orders.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/purchase-orders/purchase-orders.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/discount-code-form/discount-code-form.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/discount-code-form/discount-code-form.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/discount-code-form/discount-code-form.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/sys-admin-discount-code.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/sys-admin-discount-code.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/sys-admin-discount-code.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/sys-admin-discount-code.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  apps/shared-components/product-price-details/product-price-details.component.html
  apps/shared-components/product-price-details/product-price-details.component.scss
  apps/shared-components/product-price-details/product-price-details.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-models/contact-info.model.ts
  apps/shared-models/pricing-features.model.ts
  libs/shared/models/src/index.ts
  libs/shared/models/src/lib/contact-info.model.ts
  libs/shared/models/src/lib/db-models.enum.ts
  libs/shared/models/src/lib/discount-code.model.ts
  libs/shared/models/src/lib/product-price.model.ts
  libs/shared/models/src/lib/purchase-order.model.ts
  libs/shared/services/src/index.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/discount-codes-handler.service.ts
  libs/shared/services/src/lib/product-price.service.ts
  libs/shared/services/src/lib/purchase-order.service.ts
Labels: ready to review, backend-changes

#1887 fix: update Event Page title to 'Tech Events - Find Workshops, Hackathons & Meetups Near You'
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.ts
Labels: ready to merge

#1888 feat: user profile completion flow
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/communities-card/communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.ts
  apps/commudle-admin/src/app/components/profile-status-bar/profile-status-bar.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-one/user-profile-complete-step-one.component.html
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-one/user-profile-complete-step-one.component.scss
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-one/user-profile-complete-step-one.component.ts
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-three/user-profile-complete-step-three.component.html
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-three/user-profile-complete-step-three.component.scss
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-three/user-profile-complete-step-three.component.ts
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-two/user-profile-complete-step-two.component.html
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-two/user-profile-complete-step-two.component.scss
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/components/user-profile-complete-step-two/user-profile-complete-step-two.component.ts
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/user-profile-complete-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/user-profile-complete/user-profile-complete.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.scss
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  apps/commudle-admin/src/assets/static-assets.ts
  apps/commudle-admin/src/assets/styles/grid.scss
  apps/shared-components/tag/tag.component.ts
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.scss
  libs/shared/models/src/lib/user.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/tag.service.ts
Labels: work in progress

#1892 fix(no-admin): update sidebar visibility condition for admin user
  apps/commudle-admin/src/app/components/navbar/navbar.component.html
Labels: ready to review

#1893 fix(username): improve username validation and error handling
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/username/username.component.ts
Labels: ready to review

#1895 feat(members): add scroll functionality for speakers list and improve styling
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/members/members.component.ts
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/speakers/speaker-card/speaker-card.component.scss
Labels: ready to review
