Repository commudle/commudle-ng, pull requests merged in 2025-09, with the labels that each got.

#2072 fix: register button events desktop site
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
Labels: ready to merge, ready to review

#2076 fix(hackathon): improve problem statement HTML rendering
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-details/public-hackathon-details.component.scss
Labels: ready to merge, ready to review

#2077 feat(hackathon): enhance form functionality and user details handling
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-form.component.ts
  apps/shared-components/user-details-form/user-details-form.component.ts
Labels: ready to review

#2075 style: sitemap link to robots
  apps/commudle-admin/src/robots.txt
Labels: ready to merge, ready to review

#2086 fix: featured builds
  apps/commudle-admin/src/app/app-shared-components/featured-builds/featured-builds.component.html
Labels: ready to merge, ready to review

#2087 refactor(events): add SEO meta tags and update headers for pass scanners
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/entry-pass-scan/entry-pass-scan.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/exit-pass-scan/exit-pass-scan.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/user-event-registrations/exit-pass-scan/exit-pass-scan.component.ts
Labels: ready to review

#2084 fix(user): add WebP and HEIF support to profile image upload
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/basic-info/basic-info.component.ts
Labels: ready to review

#2088 perf(campaign): skip user engagement API calls for bots
  libs/shared/components/src/lib/components/campaign-assets-display/campaign-assets-display.component.ts
Labels: ready to review

#2090 fix: context menu dark mode and hover border on event name on admin table
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.scss
  apps/commudle-admin/src/styles.scss
  tailwind.preset.js
Labels: ready to merge, ready to review

#2091 fix: update submission condition to include hackathon end date
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-registration/public-hackathon-registration.component.ts
Labels: ready to review

#2099 fix: add event ID parameter to location tracks service
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/services/event-locations.service.ts
Labels: ready to review, backend-changes
