Repository commudle/commudle-ng, pull requests merged in 2025-07, with the labels that each got.

#1930 fix: login prompt
  apps/commudle-admin/src/app/components/login-signup/login-signup.component.html
  apps/commudle-admin/src/app/components/login-signup/login-signup.component.scss
  apps/commudle-admin/src/app/components/login-signup/login-signup.component.ts
  apps/commudle-admin/src/app/components/login/login.component.html
  apps/shared-services/login-auth.service.ts
Labels: ready to merge

#1936 style: removing justify-center from homepage expert badge
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-experts/homepage-experts.component.scss
Labels: ready to merge

#1943 fix: create event page padding and styling
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/create-event/create-event.component.scss
Labels: ready to merge

#1948 feat: implement confirmation dialog for hackathon update update deletion
  CONTRIBUTING.md
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-updates/hackathon-control-panel-updates.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-updates/hackathon-control-panel-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-updates/hackathon-control-panel-updates.component.ts
Labels: ready to review, backend-changes

#1942 feat: update event status component and add confirmation dialog for opening events
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.ts
  apps/commudle-admin/src/app/resolvers/event-details.resolver.ts
  apps/commudle-admin/src/app/services/event-data-form-entity-groups.service.ts
Labels: ready to review, backend-changes

#1950 style: update delete button styles for consistency and clarity
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.ts
Labels: ready to merge

#1952 fix: event basic details
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
Labels: ready to merge

#1953 style: faq card delete confirmation popup and round confirmation in hackathon
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.scss
  apps/shared-components/faq-card/faq-card.component.html
  apps/shared-components/faq-card/faq-card.component.scss
  apps/shared-components/faq-card/faq-card.component.ts
  apps/shared-components/faq-control-panel/faq-control-panel.component.scss
Labels: ready to merge

#1959 fix: update user profile manager service
  apps/commudle-admin/src/app/feature-modules/users/services/user-profile-manager.service.ts
Labels: ready to review

#1960 fix: community notification and notification count alignment and basic details alignemnt
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.scss
Labels: ready to merge

#1933 refactor: hackathon teammate invite
  apps/commudle-admin/src/app/app-shared-components/app-shared-components.module.ts
  apps/commudle-admin/src/app/app-shared-components/hackathon-cards/hackathon-registered-card/hackathon-registered-card.component.html
  apps/commudle-admin/src/app/app-shared-components/hackathon-cards/hackathon-registered-card/hackathon-registered-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/hackathon-cards/hackathon-registered-card/hackathon-registered-card.component.spec.ts
  apps/commudle-admin/src/app/app-shared-components/hackathon-cards/hackathon-registered-card/hackathon-registered-card.component.ts
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.scss
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-team-confirmation/hackathon-team-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/email-confirmations/email-confirmations.module.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-control-panel-speaker-judge.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-speaker-judge/hackathon-judge-card/hackathon-judge-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-judges/public-hackathon-judges.component.html
  apps/shared-models/hackathon-judge.model.ts
  libs/shared/components/src/lib/components/interested-members/interested-members.component.html
  libs/shared/components/src/lib/components/interested-members/interested-members.component.ts
  libs/shared/components/src/lib/shared-components.module.ts
  libs/shared/models/src/lib/hackathon-user-response.model.ts
Labels: ready to merge

#1969 refactor: update community builds and labs components to handling
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/services/sys-admin-labs.service.ts
  libs/shared/models/src/lib/lab.model.ts
Labels: ready to review, backend-changes

#1967 refactor: hackathon judge confirmation basic components
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-judge-confirmation/hackathon-judge-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-judge-confirmation/hackathon-judge-confirmation.component.scss
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/hackathon-judge-confirmation/hackathon-judge-confirmation.component.ts
Labels: ready to merge

#1975 feat(create-lab): integrate reCAPTCHA for lab creation form validation
  apps/commudle-admin/src/app/feature-modules/labs/components/create-lab/create-lab.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/create-lab/create-lab.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
Labels: ready to review

#1979 feat(user-job): integrate invisible reCAPTCHA for job creation
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.ts
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  libs/shared/environments/src/lib/environments.ts
Labels: ready to review

#1983 feat(sys-builds): improve builds list handling, fix permissions
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/services/sys-admin-community-builds.service.ts
  apps/commudle-admin/src/app/services/community-builds.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review

#1984 feat: integrate Google Tag Manager for campaign and checkout events tracking
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.ts
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.ts
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
Labels: ready to review

#1985 Fix(footer): twitter-icon
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.ts
Labels: ready to merge

#1986 refactor: user role confirmation (organizer, administrator, volunteer)
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/user-role-confirmation/user-role-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/user-role-confirmation/user-role-confirmation.component.scss
  apps/commudle-admin/src/app/feature-modules/email-confirmations/components/user-role-confirmation/user-role-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/email-confirmations/email-confirmations.module.ts
Labels: ready to merge

#1988 feat(user): add 410 error handling and refactor user profile fetching
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
  apps/commudle-admin/src/app/services/app-users.service.ts
  apps/lib-error-handler/src/lib/lib-error-handler.service.ts
  libs/shared/services/src/lib/api-routes.constant.ts
Labels: ready to review, backend-changes

#1961 style: modify sidebar component
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/community-groups/components/dashboard/dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-status/event-status.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.ts
  apps/commudle-admin/src/assets/store/icons-library.ts
  apps/shared-components/sidebar/enum/sidebar.enum.ts
  apps/shared-components/sidebar/sidebar.component.html
  apps/shared-components/sidebar/sidebar.component.scss
  apps/shared-components/sidebar/sidebar.component.ts
Labels: ready to merge

#1994 fix: featured-communities overlap
  apps/commudle-admin/src/app/feature-modules/communities/components/communities/communities-featured/communities-featured.component.scss
Labels: ready to merge

#1989 fix: listing pagees sidebar dark mode background and user-build backg…
  apps/shared-modules/mini-user-profile/components/profile-cards/user-profile-card-large/user-profile-card-large.component.html
Labels: ready to merge

#1992 feat(seo): enhance SEO management across admin components with noIndex and title updates
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/community-controls/community-controls.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/purchase-orders/purchase-orders.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/sys-admin-discount-code/sys-admin-discount-code.component.ts
Labels: ready to review

#1991 feat: enhance GTM event tracking by including purchase order UUID in subscription event
  apps/commudle-admin/src/app/feature-modules/pricing/components/pricing/pricing.component.ts
Labels: ready to review

#1978 fix(channels): made the hover visible over help icon
  apps/commudle-admin/src/app/app-shared-components/help-section/help-section.component.html
Labels: work in progress

#2000 refactor(prerender): add whitelisted user agents to crawler configuration
  apps/prerender/src/main.ts
Labels: ready to review

#1998 Fix: sidebar component
  apps/commudle-admin/src/app/feature-modules/events/components/event-dashboard/event-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-dashboard/hackathon-control-panel-dashboard.component.scss
  apps/shared-components/sidebar/sidebar.component.scss
Labels: ready to merge

#1990 Fix: Profile titles in the edit profile page
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/public-profile.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/communication-preferences/communication-preferences.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/cookie-preferences/cookie-preferences.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/edit-user-profile/edit-user-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/edit-user-profile/edit-user-profile.component.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
Labels: ready to merge

#2002 fix(event-card): correct date formatting to use event start time
  apps/commudle-admin/src/app/app-shared-components/event-cards/event-registered-card/event-registered-card.component.html
Labels: ready to review

#2001 fix(user): add null check before fetching user profile details
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/user-basic-details.component.ts
Labels: ready to review

#1999 fix(blogs): fixed the filters pagination
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
Labels: ready to merge

#1982 fix(Eventpage): Tooltips,labels,trackslots
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-details/event-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-location-tracks/event-location-tracks.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-locations/event-locations.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/event-registrations.component.html
Labels: ready to merge

#2011 fix(sidebar): change overflow property to allow vertical scrolling
  apps/shared-components/sidebar/sidebar.component.scss
Labels: ready to merge

#2014 Refactor(labs): display user email in labs component
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/labs/labs.component.html
Labels: ready to review

#2005 fix(event-list): made badge rounded and reusable
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.ts
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/lab-card/lab-card.component.html
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/lab-card/lab-card.component.ts
  tailwind.preset.js
Labels: ready to merge

#1973 fix(event-list): changed badge
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-events-list/community-events-list-date/community-events-list-date.component.ts
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/lab-card/lab-card.component.html
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/lab-card/lab-card.component.ts
  apps/shared-components/badge/badge.component.html
  apps/shared-components/badge/badge.component.ts
  libs/shared/environments/src/lib/environments.ts
Labels: work in progress

#2018 Revamp(profanity): add filtering and pagination to profanity terms list
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-profanity/admin-profanity.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/services/profanity.service.ts
Labels: ready to review, backend-changes

#2019 feat(user-details): add experience level and user domain checkboxes update form validation
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/new-form-attach-groups/new-form-attach-groups.component.html
  apps/shared-components/user-details-checkbox-form/user-details-checkbox-form.component.html
  apps/shared-components/user-details-checkbox-form/user-details-checkbox-form.component.ts
  apps/shared-components/user-details-form/user-details-form.component.html
  apps/shared-components/user-details-form/user-details-form.component.scss
  apps/shared-components/user-details-form/user-details-form.component.ts
Labels: ready to review

#2013 feat: hackathon listing page
  apps/commudle-admin/src/app/app-routing.module.ts
  apps/commudle-admin/src/app/app-shared-components/hackathon-horizontal-card/hackathon-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/hackathon-horizontal-card/hackathon-horizontal-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/hackathon-horizontal-card/hackathon-horizontal-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/explore-experts/explore-experts.component.scss
  apps/commudle-admin/src/app/feature-modules/dashboard/components/user-dashboard/user-dashboard.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/public-home-list-hackathons-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/public-home-list-hackathons.module.ts
  apps/shared-components/hackathon-cards/hackathon-medium-card/hackathon-medium-card.component.html
  apps/shared-components/hackathon-cards/hackathon-medium-card/hackathon-medium-card.component.scss
  apps/shared-models/hackathon.model.ts
Labels: ready to merge

#1937 fix: adding preview image to listing pages and student page
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.html
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.ts
  apps/commudle-admin/src/app/feature-modules/communities/components/communities/communities-list/communities-list.component.ts
  apps/commudle-admin/src/app/feature-modules/communities/components/communities/communities.component.html
  apps/commudle-admin/src/app/feature-modules/communities/components/communities/communities.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/community-builds.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-experts/components/public-home-list-experts/public-home-list-experts.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.ts
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.html
  apps/commudle-admin/src/app/feature-modules/student-non-profit-support/components/student-non-profit-community-support/student-non-profit-community-support.component.ts
  apps/commudle-admin/src/assets/static-assets.ts
Labels: ready to merge

#2021 Refactor(team-page): changed team page design and made modifications in radius
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/volunteers/volunteers.component.scss
Labels: ready to merge

#2027 Refactor(campaign-stats): map to show countries instead of Indian provinces
  apps/shared-components/campaign-stats/campaign-stats.component.scss
  apps/shared-components/campaign-stats/campaign-stats.component.ts
Labels: ready to review

#2026 fix(live-session): replaced image tag with banner image component
  apps/commudle-admin/src/app/feature-modules/homepage/components/homepage-events/homepage-events-card/homepage-events-card.component.html
Labels: ready to merge

#2030 refactor(build-list-item): enhance delete confirmation dialog and improve styling
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/build-list-item/build-list-item.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/build-list-item/build-list-item.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/build-list-item/build-list-item.component.ts
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/my-community-builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/my-community-builds/my-community-builds.component.ts
  apps/commudle-admin/src/app/services/stats/stats-community-builds.service.ts
  libs/shared/models/src/lib/community-build.model.ts
Labels: ready to review

#1980 Refactor(newsletter): add preview button
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.html
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.ts
Labels: ready to merge
