Repository commudle/commudle-ng, pull requests merged in 2025-08, with the labels that each got.

#2034 fix(call-for-speaker-card): changed image size
  apps/commudle-admin/src/app/app-shared-components/call-for-speaker-card/call-for-speaker-card.component.html
Labels: ready to merge, ready to review

#2041 fix: hackathon listing page fixes
  apps/commudle-admin/src/app/app-shared-components/event-mini-card/event-mini-card.component.ts
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/hackathon-horizontal-card/hackathon-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/hackathon-horizontal-card/hackathon-horizontal-card.component.scss
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.html
  apps/commudle-admin/src/app/app-shared-components/upcoming-hackathons/upcoming-hackathons.component.scss
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events/public-home-list-events.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/components/public-home-list-hackathons-homeage.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-hackathons/public-home-list-hackathons.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers/public-home-list-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/speaker-slides/speaker-slides.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/speaker-cfp/speaker-cfp.component.scss
Labels: ready to merge, ready to review

#2039 Style: implement new forms design in events public page
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-payment-details/user-payment-details.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/form-groups.component.ts
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/attending-members/attending-members.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/highlighted-links/highlighted-links.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.ts
  apps/shared-components/bottom-sheet/bottom-sheet.component.html
  apps/shared-components/bottom-sheet/bottom-sheet.component.scss
  apps/shared-components/bottom-sheet/bottom-sheet.component.ts
  apps/shared-components/payment-detail/payment-log-edfeg/payment-log-edfeg.component.html
  apps/shared-components/shared-components.module.ts
  apps/shared-models/event_data_form_enity_group.model.ts
Labels: ready to merge, ready to review, backend-changes

#2038 fix(notification page): fix notification campaign
  apps/commudle-admin/src/app/feature-modules/notifications/notifications.module.ts
Labels: ready to merge, ready to review

#2047 style: increase the width of bottom sheet bar and close the bottom sheet when clicked on line
  apps/shared-components/bottom-sheet/bottom-sheet.component.html
  apps/shared-components/bottom-sheet/bottom-sheet.component.scss
Labels: ready to merge, ready to review

#2037 fix(search-campaign): campaign alignment
  apps/commudle-admin/src/app/feature-modules/search/components/search-page-campaign/search-page-campaign.component.scss
  apps/commudle-admin/src/app/feature-modules/search/components/search-page/search-page.component.scss
Labels: ready to merge, ready to review

#2049 refactor(hackathon-control-panel): streamline tag input and validation in basic form
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.scss
Labels: ready to review

#2051 fix: horizontal scroll of email preview
  apps/commudle-admin/src/app/app-shared-components/email-preview/email-preview.component.scss
  apps/commudle-admin/src/app/app-shared-components/emailer/emailer.component.scss
Labels: ready to merge, ready to review

#2050 refactor: add location in event form and hackathon form
  apps/shared-components/user-details-form/user-details-form.component.html
  apps/shared-components/user-details-form/user-details-form.component.ts
Labels: ready to merge, ready to review

#2059 style: add user-domain, and user experience level in form responses
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.ts
Labels: ready to merge, ready to review

#2060 fix: footer-icon
  apps/commudle-admin/src/app/components/footer/footer.component.html
  apps/commudle-admin/src/app/components/footer/footer.component.ts
Labels: ready to merge

#2061 fix: Build min char length
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/create-community-build/create-community-build.component.ts
Labels: ready to merge, ready to review

#2040 style(question-card): changed design of question card with modifications
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.html
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.scss
  apps/commudle-admin/src/app/feature-modules/data-forms/components/edit-data-form/edit-data-form.component.ts
  apps/shared-components/new-data-form/new-data-form.component.html
  apps/shared-components/new-data-form/new-data-form.component.scss
  apps/shared-components/new-data-form/new-data-form.component.ts
Labels: ready to merge, ready to review

#2066 style(fill-data-form): make dialog mobile-responsive
  apps/commudle-admin/src/app/components/fill-data-form/check-fill-data-form/check-fill-data-form.component.scss
Labels: ready to review

#2067 feat(hackathon form filling): sort hackathon tracks alphabetically by name
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-project-details-form/public-hackathon-project-details-form.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.ts
Labels: ready to review

#2063 fix: add help section links
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.html
  apps/commudle-admin/src/app/app-shared-components/custom-page/custom-page-form/custom-page-form.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-edit-details/community-edit-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-surveys/community-surveys.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-surveys/community-surveys.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-stats/community-stats.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-stats/community-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/collaborating-communities/collaborating-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-agenda/event-agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-stats/event-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-basic-form/hackathon-control-panel-basic-form.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/create-lab/create-lab.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/components/public-home-list-speakers-profile/public-home-list-speakers-profile.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-speakers/public-home-list-speakers.module.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/public-events.module.ts
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.scss
  apps/commudle-admin/src/app/feature-modules/users/users.module.ts
  libs/shared/services/src/lib/help-dictionary.store.ts
Labels: ready to merge, ready to review

#2069 style: change info box text to title case
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
Labels: ready to merge, ready to review
