Repository commudle/commudle-ng, pull requests merged in 2025-01, with the labels that each got.

#1704 Refactor: blogs page
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
Labels: ready to merge

#1706 style: job schema for job-list component
  apps/commudle-admin/src/app/feature-modules/jobs/components/job-list/job-list.component.ts
Labels: ready to merge

#1698 refactor: sidebar community page
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/admin-community-hackathon/admin-community-hackathon.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-and-surveys.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-and-surveys.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-forms-list/community-forms-list.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-surveys/community-surveys.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-surveys/community-surveys.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-forms-and-surveys/community-surveys/community-surveys.component.ts
Labels: ready to merge

#1708 fix: line height in blogs heading
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.scss
Labels: ready to review

#1710 style: orgs logo community
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.scss
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
  libs/shared/models/src/lib/community.model.ts
Labels: ready to merge

#1712 fix: clone events
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.html
Labels: ready to merge

#1713 refactor: blogs page
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog-card/blog-card.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/models/blogs.model.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/public-blogs.module.ts
Labels: ready to merge

#1714 fix: events comments schema data
  apps/shared-components/messages/messages-list/message/message.component.ts
  apps/shared-components/messages/messages-list/messages-list.component.ts
Labels: ready to merge

#1716 style: remove mini footer from events page
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
Labels: ready to merge

#1718 fix: provide default description for job postings Schema Data
  apps/commudle-admin/src/app/feature-modules/jobs/components/job/job.component.ts
Labels: work in progress

#1719 feat: enhance event schema with description and performer details
  apps/commudle-admin/src/app/feature-modules/public-community/components/events/events.component.ts
Labels: work in progress

#1722 style: update channel settings layout and styling
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.html
  apps/commudle-admin/src/app/feature-modules/community-channels/components/channel-settings/channel-settings.component.scss
Labels: ready to review

#1724 refactor: blogs structured tags and pagination
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
  apps/shared-services/cms.service.ts
Labels: ready to review

#1726 feat: add SEO schema for lab details
  apps/commudle-admin/src/app/feature-modules/labs/components/lab/lab.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-search/labs-search.component.ts
Labels: ready to review

#1725 style: make tiny mce sticky on edit lab
  apps/commudle-admin/src/app/feature-modules/labs/components/edit-lab/edit-lab.component.scss
Labels: ready to review

#1727 fix: update blogs list component to use total for pagination
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.html
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.scss
Labels: ready to merge

#1731 style: remove disabled from clone events
  apps/commudle-admin/src/app/feature-modules/events/components/edit-event/edit-event.component.ts
Labels: ready to merge

#1728 fix: sanitize 'about' field in search details component
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.html
  apps/commudle-admin/src/app/feature-modules/search/components/search-details/search-details.component.ts
Labels: ready to review

#1729 feat: add Community Mails Sent Stats component
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel-routing.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/community-control-panel.module.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-mails-sent-stats/community-mails-sent-stats.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-mails-sent-stats/community-mails-sent-stats.component.scss
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-mails-sent-stats/community-mails-sent-stats.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-mails-sent-stats/community-mails-sent-stats.component.ts
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.scss
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.ts
Labels: ready to review

#1730 style: add custom window class for email preview and update styles
  apps/commudle-admin/src/app/feature-modules/reusable-components/components/community-emails-list/community-emails-list.component.ts
  apps/commudle-admin/src/styles.scss
Labels: ready to review

#1732 fix: update header variation logic
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.html
  apps/commudle-admin/src/app/feature-modules/public-community/components/home-community/home-community.component.ts
Labels: ready to review

#1717 style: add comments schema data
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-chat/session-page-chat.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-chat/session-page-chat.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/session-page/session-page-video/session-page-video.component.html
  apps/commudle-admin/src/app/feature-modules/speaker-resources/components/speaker-resource/speaker-resource.component.html
  apps/shared-components/messages/messages-list/messages-list.component.ts
  apps/shared-components/messages/messages.component.html
  apps/shared-components/messages/messages.component.ts
Labels: ready to merge

#1733 fix: add minimum price validation for ticket settings
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.html
  apps/commudle-admin/src/app/feature-modules/events/components/event-registrations/form-groups/payment-settings/payment-settings.component.ts
Labels: ready to review

#1734 Refactor blog schema
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blog/blog.component.ts
  apps/commudle-admin/src/app/feature-modules/public-blogs/components/blogs-list/blogs-list.component.ts
Labels: ready to review

#1723 fix: add userId binding to follow button and improve rtmp_url check
  apps/shared-modules/hms-video/components/hms-video/conference/conference-user-videos/conference-user-video/conference-user-video.component.html
  apps/shared-modules/hms-video/components/hms-video/conference/conference.component.html
Labels: ready to review

#1738 refactor: add alert for image width guidelines in newsletter form
  apps/commudle-admin/src/app/app-shared-components/newsletter/newsletter-form/newsletter-form.component.html
Labels: ready to review

#1737 feat: implement pagination for user responses in hackathon control panel
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-tracks-prizes/hackathon-control-panel-prize/hackathon-prize-card/hackathon-prize-card.component.ts
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-form/public-hackathon-teammate-form/public-hackathon-teammate-form.component.html
  apps/commudle-admin/src/app/services/hackathon.service.ts
Labels: ready to review, backend-changes

#1741 Style: builds schema data
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-builds/builds/builds.component.ts
Labels: ready to merge

#1740 style: header images events page
  apps/commudle-admin/src/app/app-shared-components/event-horizontal-card/event-horizontal-card.component.html
  apps/commudle-admin/src/app/app-shared-components/featured-communities-card/featured-communities-card.component.html
Labels: ready to merge
