Repository commudle/commudle-ng, pull requests merged in 2025-02, with the labels that each got.

#1743 feat: enhance hackathon control panel review with loading spinner
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.scss
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
Labels: ready to review

#1744 feat: add loading state for personal chats in user chats component
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-container/chats-container.component.ts
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.html
  apps/commudle-admin/src/app/feature-modules/user-chats/components/chats-list/chats-list.component.ts
  libs/editor/src/lib/components/editor/editor.component.html
  libs/editor/src/lib/components/editor/editor.component.scss
  libs/editor/src/lib/components/editor/editor.component.ts
Labels: ready to review

#1746 Style: navbar
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.html
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.scss
  apps/commudle-admin/src/app/components/navbar-menu/navbar-menu.component.ts
  apps/commudle-admin/src/app/components/navbar/navbar.component.html
  apps/commudle-admin/src/app/components/navbar/navbar.component.scss
Labels: ready to merge

#1748 style: add fragments on events page
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-past/public-home-list-events-past.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-speakers/public-home-list-events-speakers.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-tech-sessions/public-home-list-events-tech-sessions.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-upcoming/public-home-list-events-upcoming/public-home-list-events-upcoming.component.ts
Labels: ready to merge

#1749 refactor: listing page header
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.html
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.scss
  apps/shared-models/listing-page-header.model.ts
Labels: ready to merge

#1750 fix: channel redirect issue
  apps/commudle-admin/src/app/feature-modules/community-channels/components/email-join/email-join.component.ts
  libs/shared/models/src/lib/community-channel.model.ts
Labels: ready to review

#1754 fix: remove border from featured communities
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-featured-communities/public-home-list-events-featured-communities.component.scss
Labels: ready to merge

#1753 fix: events listing page header
  apps/commudle-admin/src/app/app-shared-components/listing-page-header/listing-page-header.component.scss
Labels: ready to merge

#1752 feat: show schema data to all
  libs/shared/services/src/lib/seo.service.ts
Labels: ready to review

#1757 style: add spacing between hackathon meta title
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-homepage/public-hackathon-homepage.component.ts
Labels: ready to merge

#1755 style: labs listing page header and delete events-header
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.html
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.scss
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs-header/labs-header.component.ts
  apps/commudle-admin/src/app/feature-modules/labs/components/labs/labs.component.html
  apps/commudle-admin/src/app/feature-modules/labs/labs.module.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.html
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.scss
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.spec.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/components/public-home-list-events-header/public-home-list-events-header.component.ts
  apps/commudle-admin/src/app/feature-modules/listing-pages/public-home-list-events/public-home-list-events.module.ts
Labels: ready to merge

#1758 feat: add ngx-markdown support for privacy policy content rendering
  apps/commudle-admin/src/app/feature-modules/policies/component/policies/policies.component.html
  apps/commudle-admin/src/app/feature-modules/policies/policies.module.ts
  apps/shared-models/privacy.model.ts
  package-lock.json
  package.json
Labels: ready to review

#1756 style: brand guidelines in footer
  apps/commudle-admin/src/app/components/footer/footer.component.html
Labels: ready to review

#1760 style: community header
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
Labels: ready to merge

#1761 refactor: fragments events page
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/agenda/agenda.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/collaboration-communities/collaboration-communities.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/collaboration-communities/collaboration-communities.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-description/event-description.component.ts
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/event-updates/event-updates.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/home-event/home-event.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/speakers/speakers.component.scss
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.html
  apps/commudle-admin/src/app/feature-modules/public-events/components/team/team.component.scss
Labels: ready to merge

#1766 style: fragments profile page
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-social/user-basic-social.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-badges/user-badges.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-contributions/user-contributions.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-job/user-job.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-resume/user-resume.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-social/user-social.component.scss
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-extra-details/user-work-history/user-work-history.component.scss
Labels: ready to merge

#1768 fix: margin in community admin dashboard
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.html
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-control-panel/community-control-panel.component.scss
Labels: ready to merge

#1765 refactor: update message deletion logic
  libs/shared/components/src/lib/components/channel-discussion/community-channel-message/community-channel-message.component.ts
  libs/shared/components/src/lib/components/channel-discussion/community-forum-message/community-forum-message.component.ts
  libs/shared/components/src/lib/services/community-channel-handler.service.ts
  libs/shared/services/src/lib/seo.service.ts
Labels: ready to review

#1763 fix: close dialog after round creation/update
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-rounds/hackathon-control-panel-rounds.component.ts
Labels: ready to review

#1769 style: add edit button on build
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.html
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.scss
  apps/commudle-admin/src/app/feature-modules/community-builds/components/community-build/community-build-details/community-build-details.component.ts
Labels: ready to merge

#1770 feat: add loading state management for payment processes
  apps/commudle-admin/src/app/components/fill-data-form/fill-data-form-paid/fill-data-form-paid.component.ts
Labels: ready to review

#1762 feat: add URL validation and error alerts for social links
  apps/commudle-admin/src/app/feature-modules/events/components/event-form-responses/user-details-cell/user-details-cell.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/social-links/social-links.component.html
  apps/commudle-admin/src/app/feature-modules/users/components/public-profile/user-basic-details/basic-user-profile/social-links/social-links.component.ts
  apps/shared-components/form-responses/responses-table/user-details-cell/user-details-cell.component.html
Labels: ready to review

#1773 fix: change account number input type from number to text
  apps/commudle-admin/src/app/feature-modules/community-control-panel/components/community-payments/community-bank-details/community-bank-details.component.html
Labels: ready to review

#1771 feat: add pagination to public hackathon projects component
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-projects/public-hackathon-projects.component.html
  apps/commudle-admin/src/app/feature-modules/public-hackathon/components/public-hackathon-projects/public-hackathon-projects.component.ts
  apps/commudle-admin/src/app/services/hackathon.service.ts
Labels: ready to review, backend-changes

#1776 fix: search box overlapping text
  apps/commudle-admin/src/app/feature-modules/search/components/search-box/search-box.component.scss
Labels: ready to merge

#1747 fix: past events image sizing
  apps/commudle-admin/src/app/app-shared-components/event-card/event-card.component.html
Labels: ready to review, backend-changes

#1775 Feat campaigns
  apps/commudle-admin/src/app/feature-modules/admin-campaign/admin-campaign.module.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-confirmation/campaign-form-order-confirmation.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-order-setup/campaign-form-order-setup.component.ts
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.html
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form-select-campaign/campaign-form-select-campaign.component.scss
  apps/commudle-admin/src/app/feature-modules/admin-campaign/components/campaign-form/campaign-form.component.html
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.html
  apps/commudle-admin/src/app/feature-modules/payment-checkout/components/checkout-page/checkout-page.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.html
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.scss
  apps/commudle-admin/src/app/feature-modules/sys-admin/components/admin-campaigns/campaign-types/campaign-types.component.ts
  apps/commudle-admin/src/app/feature-modules/sys-admin/sys-admin.module.ts
  apps/shared-components/campaign-details/campaign-details.component.html
  apps/shared-components/campaign-details/campaign-details.component.scss
  apps/shared-components/campaign-details/campaign-details.component.spec.ts
  apps/shared-components/campaign-details/campaign-details.component.ts
  apps/shared-components/campaign-list/campaign-list.component.html
  apps/shared-components/campaign-list/campaign-list.component.scss
  apps/shared-components/campaign-list/campaign-list.component.ts
  apps/shared-components/shared-components.module.ts
  apps/shared-components/tag/tag.component.html
  apps/shared-components/tag/tag.component.ts
  libs/shared/components/src/lib/components/input/input.component.ts
  libs/shared/models/src/lib/campaign.model.ts
  libs/shared/services/src/lib/api-routes.constant.ts
  libs/shared/services/src/lib/campaign.service.ts
Labels: ready to merge

#1777 fix: update note handling to use selected user response
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.html
  apps/commudle-admin/src/app/feature-modules/hackathon-control-panel/components/hackathon-control-panel-review/hackathon-control-panel-review.component.ts
Labels: ready to review
